<?php
/* Full Example
	"Nekomonogatari (Kuro): Tsubasa Family" => [
		"Opening 1" => [
			"file" => "Opening1-NekomonogatariKuro.webm",
			"song" => [
				"title" => "perfect slumbers",
				"artist" => "Yui Horie"],
			"subtitles" => "Commie"],
		"Ending 1a" => [
			"file" => "Ending1a-NekomonogatariKuro.webm",
			"song" => [
				"title" => "Kieru Daydream (消えるdaydream)",
				"artist" => "Marina Kawano"]],
		"Ending 1b" => [
			"file" => "Ending1b-NekomonogatariKuro.webm"]],
*/
$names = [
	".hack//Sign" => [
		"Opening 1" => [
			"file" => "Opening1-DotHackSign.webm",
			"song" => [
				"title" => "Obsession",
				"artist" => "See-Saw"]]],
	"Accel World" => [
		"Opening 1" => [
			"file" => "Opening1-AccelWorld.webm"],
		"Opening 2" => [
			"file" => "Opening2-AccelWorld.webm"],
		"Ending 1" => [
			"file" => "Ending1-AccelWorld.webm"],
		"Ending 2" => [
			"file" => "Ending2-AccelWorld.webm"]],
	"Acchi Kocchi" => [
		"Opening 1" => [
			"file" => "Opening1-AcchiKocchi.webm"],
		"Ending 1" => [
			"file" => "Ending1-AcchiKocchi.webm"]],
	"Akagi" => [
		"Opening 1" => [
			"file" => "Opening1-Akagi.webm"],
		"Ending 1" => [
			"file" => "Ending1-Akagi.webm"],
		"Ending 2" => [
			"file" => "Ending2-Akagi.webm"]],
	"Akame ga Kill" => [
		"Opening 1" => [
			"file" => "Opening1-AkameGaKill.webm"],
		"Opening 2" => [
			"file" => "Opening2-AkameGaKill.webm"]],
	"AKB0048" => [
		"Opening 1" => [
			"file" => "Opening1-AKB0048.webm"],
		"Ending 1" => [
			"file" => "Ending1-AKB0048.webm"]],
	"Aldnoah.Zero" => [
		"Opening 1" => [
			"file" => "Opening1-AldnoahZero.webm",
			"song" => [
				"title" => "Heavenly Blue",
				"artist" => "Kalafina"]],
		"Opening 2" => [
			"file" => "Opening2-AldnoahZero.webm"],
		"Ending 1" => [
			"file" => "Ending1-AldnoahZero.webm",
			"song" => [
				"title" => "A/Z",
				"artist" => "Hiroyuki Sawano (sung by Mizuki)"]],
		"Ending 2" => [
			"file" => "Ending2-AldnoahZero.webm"],
		"Ending 3" => [
			"file" => "Ending3-AldnoahZero.webm"],
		"Ending 4" => [
			"file" => "Ending4-AldnoahZero.webm"]],
	"Amagami SS" => [
		"Opening 1" => [
			"file" => "Opening1-AmagamiSS.webm"],
		"Opening 4" => [
			"file" => "Opening4-AmagamiSS.webm"],
		"Ending 1" => [
			"file" => "Ending1-AmagamiSS.webm"],
		"Ending 2" => [
			"file" => "Ending2-AmagamiSS.webm"]],
	"Amagi Brilliant Park" => [
		"Opening 1" => [
			"file" => "Opening1-AmagiBrilliantPark.webm"],
		"Ending 1" => [
			"file" => "Ending1-AmagiBrilliantPark.webm"]],
	"Angel Beats" => [
		"Opening 1" => [
			"file" => "Opening1-AngelBeats.webm"]],
	"Anohana (The Flower We Saw That Day)" => [
		"Opening 1" => [
			"file" => "Opening1-Anohana.webm"],
		"Ending 1" => [
			"file" => "Ending1-Anohana.webm"]],
	"Another" => [
		"Opening 1" => [
			"file" => "Opening1-Another.webm"],
		"Ending 1" => [
			"file" => "Ending1-Another.webm"]],
	"Ansatsu Kyoushitsu" => [
		"Opening 1" => [
			"file" => "Opening1-AnsatsuKyoushitsu.webm"],
		"Ending 1" => [
			"file" => "Ending1-AnsatsuKyoushitsu.webm"]],
	"Aoi Hana" => [
		"Opening 1" => [
			"file" => "Opening1-AoiHana.webm"],
		"Ending 1" => [
			"file" => "Ending1-AoiHana.webm"]],
	"Ao no Exorcist (Blue Exorcist)" => [
		"Opening 1" => [
			"file" => "Opening1-AoNoExorcist.webm"],
		"Opening 2" => [
			"file" => "Opening2-AoNoExorcist.webm"],
		"Ending 1" => [
			"file" => "Ending1-AoNoExorcist.webm"],
		"Ending 2" => [
			"file" => "Ending2-AoNoExorcist.webm"]],
	"Arakawa Under the Bridge" => [
		"Opening 1" => [
			"file" => "Opening1-ArakawaUnderTheBridge.webm"],
		"Opening 2" => [
			"file" => "Opening2-ArakawaUnderTheBridge.webm"]],
	"Arpeggio of Blue Steel: Ars Nova" => [
		"Opening 1" => [
			"file" => "Opening1-ArpeggioOfBlueSteelArsNova.webm"],
		"Ending 1" => [
			"file" => "Ending1-ArpeggioOfBlueSteelArsNova.webm"]],
	"Atelier Escha & Logy: Alchemists of the Dusk Sky" => [
		"Opening 1" => [
			"file" => "Opening1-AtelierEschaLogy.webm"],
		"Ending 1" => [
			"file" => "Ending1-AtelierEschaLogy.webm"]],
	"Attack on Titan (Shingeki no Kyojin)" => [
		"Opening 1a" => [
			"file" => "Opening1a-AttackOnTitan.webm"],
		"Opening 2" => [
			"file" => "Opening2-AttackOnTitan.webm"],
		"Ending 1" => [
			"file" => "Ending1-AttackOnTitan.webm"],
		"Ending 2a" => [
			"file" => "Ending2a-AttackOnTitan.webm"]],
	"Azumanga Daioh" => [
		"Opening 1" => [
			"file" => "Opening1-AzumangaDaioh.webm"],
		"Ending 1" => [
			"file" => "Ending1-AzumangaDaioh.webm"]],
	"Baccano!" => [
		"Opening 1" => [
			"file" => "Opening1-Baccano.webm"],
		"Ending 1" => [
			"file" => "Ending1-Baccano.webm"]],
	"Bakemonogatari" => [
		"Hitagi Crab Opening" => [
			"file" => "Opening1-Bakemonogatari.webm",
			"song" => [
				"title" => "Staple Stable",
				"artist" => "Chiwa Saito"]],
		"Mayoi Snail Opening" => [
			"file" => "Opening2-Bakemonogatari.webm",
			"song" => [
				"title" => "Kaerimichi",
				"artist" => "Emiri Kato"]],
		"Suruga Monkey Opening" => [
			"file" => "Opening3-Bakemonogatari.webm",
			"song" => [
				"title" => "Ambivalent World",
				"artist" => "Miyuki Sawashiro"]],
		"Nadeko Snake Opening a" => [
			"file" => "Opening4a-Bakemonogatari.webm",
			"song" => [
				"title" => "Ren'ai Circulation",
				"artist" => "Kana Hanazawa"]],
		"Nadeko Snake Opening b" => [
			"file" => "Opening4b-Bakemonogatari.webm",
			"song" => [
				"title" => "Ren'ai Circulation",
				"artist" => "Kana Hanazawa"]],
		"Tsubasa Cat Opening a" => [
			"file" => "Opening5a-Bakemonogatari.webm",
			"song" => [
				"title" => "Sugar Sweet Nightmare",
				"artist" => "Yui Horie"]],
		"Tsubasa Cat Opening b" => [
			"file" => "Opening5b-Bakemonogatari.webm",
			"song" => [
				"title" => "Sugar Sweet Nightmare",
				"artist" => "Yui Horie"]],
		"Hitagi Crab and Suruga Monkey Ending" => [
			"file" => "Ending1a-Bakemonogatari.webm",
			"song" => [
				"title" => "Kimi no Shiranai Monogatari",
				"artist" => "Supercell"]],
		"Nadeko Snake Ending" => [
			"file" => "Ending1d-Bakemonogatari.webm",
			"song" => [
				"title" => "Kimi no Shiranai Monogatari",
				"artist" => "Supercell"]],
		"Tsubasa Cat Ending a" => [
			"file" => "Ending1e-Bakemonogatari.webm",
			"song" => [
				"title" => "Kimi no Shiranai Monogatari",
				"artist" => "Supercell"]],
		"Tsubasa Cat Ending c" => [
			"file" => "Ending1g-Bakemonogatari.webm",
			"song" => [
				"title" => "Kimi no Shiranai Monogatari",
				"artist" => "Supercell"]]],
	"Barakamon" => [
		"Opening 1" => [
			"file" => "Opening1-Barakamon.webm"],
		"Ending 1" => [
			"file" => "Ending1-Barakamon.webm"]],
	"Basilisk" => [
		"Opening 1" => [
			"file" => "Opening1-Basilisk.webm",
			"song" => [
				"title" => "Kouga Ninpouchou",
				"artist" => "Onmyouza"]],
		"Ending 1" => [
			"file" => "Ending1-Basilisk.webm",
			"song" => [
				"title" => "Hime Murasaki",
				"artist" => "Nana Mizuki"]],
		"Ending 2" => [
			"file" => "Ending2-Basilisk.webm",
			"song" => [
				"title" => "Wild Eyes",
				"artist" => "Nana Mizuki"]]],
	"Battle Programmer Shirase" => [
		"Opening 1" => [
			"file" => "Opening1-BattleProgrammerShirase.webm"],
		"Ending 1" => [
			"file" => "Ending1-BattleProgrammerShirase.webm"]],
	"Beck" => [
		"Opening 1" => [
			"file" => "Opening1-Beck.webm"],
		"Ending 1" => [
			"file" => "Ending1-Beck.webm"]],
	"Black Bullet" => [
		"Opening 1a" => [
			"file" => "Opening1a-BlackBullet.webm"],
		"Opening 1b" => [
			"file" => "Opening1b-BlackBullet.webm"],
		"Ending 1" => [
			"file" => "Ending1-BlackBullet.webm"]],
	"Black Rock Shooter" => [
		"Opening 1" => [
			"file" => "Opening1-BlackRockShooter.webm"]],
	"Blade and Soul" => [
		"Opening 1" => [
			"file" => "Opening1-BladeAndSoul.webm"]],
	"Blood Lad" => [
		"Opening 1" => [
			"file" => "Opening1-BloodLad.webm"],
		"Ending 1" => [
			"file" => "Ending1-BloodLad.webm"]],
	"Bokurano" => [
		"Opening 1" => [
			"file" => "Opening1-Bokurano.webm"],
		"Ending 1" => [
			"file" => "Ending1-Bokurano.webm"],
		"Ending 2" => [
			"file" => "Ending2-Bokurano.webm"]],
	"Boku wa Tomodachi ga Sukunai (Haganai)" => [
		"Opening 1" => [
			"file" => "Opening1-BokuWaTomodachiGaSukunai.webm",
			"song" => [
				"title" => "Zannenkei Rinjinbu (Hoshi Futatsu Han) (残念系隣人部★★☆(星ふたつ半))",
				"artist" => "Tomodachi Tsukuritai (友達つくり隊)"]],
		"Ending 1" => [
			"file" => "Ending1-BokuWaTomodachiGaSukunai.webm",
			"song" => [
				"title" => "Watashi no Kimochi (私のキ・モ・チ)",
				"artist" => "Marina Inoue"]]],
	"Boku wa Tomodachi ga Sukunai (Haganai) NEXT" => [
		"Opening 1" => [
			"file" => "Opening1-BokuWaTomodachiGaSukunaiNEXT.webm",
			"song" => [
				"title" => "Be My Friend",
				"artist" => "The Neighbor's Club (隣人部)"]],
		"Ending 1a" => [
			"file" => "Ending1a-BokuWaTomodachiGaSukunaiNEXT.webm",
			"song" => [
				"title" => "Bokura no Tsubasa (僕らの翼)",
				"artist" => "The Neighbor's Club (隣人部)"]],
		"Ending 1b" => [
			"file" => "Ending1b-BokuWaTomodachiGaSukunaiNEXT.webm",
			"song" => [
				"title" => "Bokura no Tsubasa (僕らの翼)",
				"artist" => "The Neighbor's Club (隣人部)"]]],
	"Btooom!" => [
		"Ending 1" => [
			"file" => "Ending1-Btooom!.webm"]],
	"C3: Cube x Cursed x Curious" => [
		"Opening 1" => [
			"file" => "Opening1-CubexCursedxCurious.webm"],
		"Opening 2" => [
			"file" => "Opening2-CubexCursedxCurious.webm"],
		"Ending 1" => [
			"file" => "Ending1-CubexCursedxCurious.webm"],
		"Ending 2" => [
			"file" => "Ending2-CubexCursedxCurious.webm"]],
	"C: The Money of Soul and Possibility Control" => [
		"Opening 1" => [
			"file" => "Opening1-CTheMoneyOfSoulAndPossibilityControl.webm"],
		"Ending 1" => [
			"file" => "Ending1-CTheMoneyOfSoulAndPossibilityControl.webm"]],
	"Canaan" => [
		"Opening 1" => [
			"file" => "Opening1-Canaan.webm"]],
	"Cardcaptor Sakura" => [
		"Opening 1a" => [
			"file" => "Opening1a-CardcaptorSakura.webm"],
		"Opening 1b" => [
			"file" => "Opening1b-CardcaptorSakura.webm"],
		"Opening 2" => [
			"file" => "Opening2-CardcaptorSakura.webm"],
		"Opening 3" => [
			"file" => "Opening3-CardcaptorSakura.webm"],
		"Ending 1" => [
			"file" => "Ending1-CardcaptorSakura.webm"],
		"Ending 2" => [
			"file" => "Ending2-CardcaptorSakura.webm"],
		"Ending 3" => [
			"file" => "Ending3-CardcaptorSakura.webm"]],
	"Carnival Phantasm" => [
		"Opening 1" => [
			"file" => "Opening1-CarnivalPhantasm.webm"]],
	"Chuunibyou demo Koi ga Shitai!" => [
		"Opening 1" => [
			"file" => "Opening1-Chuunibyou.webm"],
		"Opening 2" => [
			"file" => "Opening2-Chuunibyou.webm"],
		"Ending 1" => [
			"file" => "Ending1-Chuunibyou.webm"],
		"Ending 2" => [
			"file" => "Ending2-Chuunibyou.webm"]],
	"Clannad" => [
		"Opening 1" => [
			"file" => "Opening1-Clannad.webm"],
		"Ending 1" => [
			"file" => "Ending1-Clannad.webm"]],
	"Clannad: After Story" => [
		"Opening 1" => [
			"file" => "Opening1-ClannadAfterStory.webm"],
		"Ending 1a" => [
			"file" => "Ending1a-ClannadAfterStory.webm"],
		"Ending 1c" => [
			"file" => "Ending1c-ClannadAfterStory.webm"],
		"Ending 1d" => [
			"file" => "Ending1d-ClannadAfterStory.webm"]],
	"Code Geass" => [
		"Opening 1" => [
			"file" => "Opening1-CodeGeassR1.webm"],
		"Opening 2" => [
			"file" => "Opening2-CodeGeassR1.webm"],
		"Opening 3" => [
			"file" => "Opening3-CodeGeassR1.webm"],
		"Ending 1" => [
			"file" => "Ending1-CodeGeassR1.webm"],
		"Ending 2" => [
			"file" => "Ending2-CodeGeassR1.webm"]],
	"Code Geass R2" => [
		"Opening 1" => [
			"file" => "Opening1-CodeGeassR2.webm"],
		"Opening 2" => [
			"file" => "Opening2-CodeGeassR2.webm"],
		"Ending 1" => [
			"file" => "Ending1-CodeGeassR2.webm"],
		"Ending 2" => [
			"file" => "Ending2-CodeGeassR2.webm"]],
	"Corpse Party" => [
		"Game Opening" => [
			"file" => "Opening1-CorpseParty.webm"]],
	"Corpse Party: Book of Shadows" => [
		"Game Opening" => [
			"file" => "Opening1-CorpsePartyBookOfShadows.webm"]],
	"Cowboy Bebop" => [
		"Opening 1" => [
			"file" => "Opening1-CowboyBebop.webm"]],
	"Damekko Doubutsu" => [
		"Opening 1" => [
			"file" => "Opening1-DamekkoDoubutsu.webm",
			"song" => [
				"title" => "Sekai de Ichiban Boku ga Suki!",
				"artist" => "Shintani Ryoko"]],
		"Ending 1" => [
			"file" => "Ending1-DamekkoDoubutsu.webm",
			"song" => [
				"title" => "Life is Free",
				"artist" => "unknown"]]],
	"Danganronpa: The Animation" => [
		"Opening 2" => [
			"file" => "Opening2-DanganronpaTheAnimation.webm"]],
	"Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka (Danmachi)" => [
		"Opening 1" => [
			"file" => "Opening1-Danmachi.webm"]],
	"Danshi Koukousei no Nichijou" => [
		"Opening 1" => [
			"file" => "Opening1-DanshiKoukouseiNoNichijou.webm"],
		"Ending 1" => [
			"file" => "Ending1-DanshiKoukouseiNoNichijou.webm"],
		"Ending 2" => [
			"file" => "Ending2-DanshiKoukouseiNoNichijou.webm"]],
	"Darker than Black" => [
		"Opening 1" => [
			"file" => "Opening1-DarkerThanBlack.webm"],
		"Opening 2" => [
			"file" => "Opening2-DarkerThanBlack.webm"],
		"Ending 1" => [
			"file" => "Ending1-DarkerThanBlack.webm"],
		"Ending 2" => [
			"file" => "Ending2-DarkerThanBlack.webm"]],
	"Darker than Black: Ryuusei no Gemini" => [
		"Opening 1" => [
			"file" => "Opening1-DarkerThanBlackRyuuseiNoGemini.webm"],
		"Ending 1" => [
			"file" => "Ending1-DarkerThanBlackRyuuseiNoGemini.webm"]],
	"Deadman Wonderland" => [
		"Opening 1" => [
			"file" => "Opening1-DeadmanWonderland.webm"],
		"Ending 1" => [
			"file" => "Ending1-DeadmanWonderland.webm"]],
	"Death Parade" => [
		"Opening 1" => [
			"file" => "Opening1-DeathParade.webm"]],
	"Denpa Onna to Seishun Otoko" => [
		"Opening 1" => [
			"file" => "Opening1-DenpaOnnaToSeishunOtoko.webm"],
		"Ending 1" => [
			"file" => "Ending1-DenpaOnnaToSeishunOtoko.webm"]],
	"Digimon Tamers" => [
		"Opening 1a" => [
			"file" => "Opening1a-DigimonTamers.webm",
			"song" => [
				"title" => "The Biggest Dreamer",
				"artist" => "Kouji Wada"]],
		"Ending 1" => [
			"file" => "Ending1-DigimonTamers.webm",
			"song" => [
				"title" => "My Tomorrow",
				"artist" => "AiM"]],
		"Ending 2" => [
			"file" => "Ending2-DigimonTamers.webm",
			"song" => [
				"title" => "Days~Aijou to Nichijou~",
				"artist" => "AiM"]]],
	"Dog Days" => [
		"Opening 1" => [
			"file" => "Opening1-DogDays.webm"],
		"Ending 1" => [
			"file" => "Ending1-DogDays.webm"]],
	"Dragon Ball Kai" => [
		"Opening 1" => [
			"file" => "Opening1-DragonballKai.webm"],
		"Ending 1" => [
			"file" => "Ending1-DragonballKai.webm"],
		"Ending 2" => [
			"file" => "Ending2-DragonballKai.webm"]],
	"Dragon Crisis" => [
		"Opening 1" => [
			"file" => "Opening1-DragonCrisis.webm",
			"song" => [
				"title" => "Immoralist (インモラリスト)",
				"artist" => "Yui Horie"]],
		"Ending 1" => [
			"file" => "Ending1-DragonCrisis.webm",
			"song" => [
				"title" => "Mirai Bowl (ミライボウル)",
				"artist" => "Momoiro Clover"]]],
	"Durarara!!" => [
		"Opening 1" => [
			"file" => "Opening1-Durarara!!.webm",
			"song" => [
				"title" => "裏切りの夕焼け (Uragiri no Yuuyake)",
				"artist" => "THEATRE BROOK"]],
		"Opening 2" => [
			"file" => "Opening2-Durarara!!.webm",
			"song" => [
				"title" => "コンプリケイション (Complication)",
				"artist" => "ROOKiEZ is PUNK'D"]],
		"Ending 1" => [
			"file" => "Ending1-Durarara!!.webm",
			"song" => [
				"title" => "Trust Me",
				"artist" => "松下優也 (Yuya Matsushita)"]],
		"Ending 2" => [
			"file" => "Ending2-Durarara!!.webm",
			"song" => [
				"title" => "Butterfly",
				"artist" => "On/Off"]]],
	"Durarara!! X2" => [
		"Opening 1" => [
			"file" => "Opening1-Durarara!!X2.webm"],
		"Ending 1" => [
			"file" => "Ending1-Durarara!!X2.webm"]],
	"Dysfunctional Systems: Learning to Manage Chaos" => [
		"Game Opening" => [
			"file" => "Opening1-DysfunctionalSystemsLearningToManageChaos.webm"]],
	"Eden of the East" => [
		"Opening 1" => [
			"file" => "Opening1-EdenOfTheEast.webm"],
		"Ending 1" => [
			"file" => "Ending1-EdenOfTheEast.webm"]],
	"Ef - a Tale of Melodies." => [
		"Opening 1" => [
			"file" => "Opening1-EfATaleOfMelodies.webm"],
		"Ending 1" => [
			"file" => "Ending1-EfATaleOfMelodies.webm"],
		"Ending 2" => [
			"file" => "Ending2-EfATaleOfMelodies.webm"],
		"Ending 3" => [
			"file" => "Ending3-EfATaleOfMelodies.webm"],
		"Ending 4" => [
			"file" => "Ending4-EfATaleOfMelodies.webm"],
		"Ending 5" => [
			"file" => "Ending5-EfATaleOfMelodies.webm"]],
	"Ef - a Tale of Memories." => [
		"Opening 1" => [
			"file" => "Opening1-EfATaleOfMemories.webm"],
		"Opening 2" => [
			"file" => "Opening2-EfATaleOfMemories.webm"],
		"Ending 1a" => [
			"file" => "Ending1a-EfATaleOfMemories.webm"],
		"Ending 1b" => [
			"file" => "Ending1b-EfATaleOfMemories.webm"],
		"Ending 2" => [
			"file" => "Ending2-EfATaleOfMemories.webm"],
		"Ending 3" => [
			"file" => "Ending3-EfATaleOfMemories.webm"]],
	"Elfen Lied" => [
		"Opening 1" => [
			"file" => "Opening1-ElfenLied.webm"],
		"Ending 1" => [
			"file" => "Ending1-ElfenLied.webm"]],
	"Ergo Proxy" => [
		"Opening 1" => [
			"file" => "Opening1-ErgoProxy.webm"]],
	"Etotama" => [
		"Opening 1" => [
			"file" => "Opening1-Etotama.webm",
			"song" => [
				"title" => "Retry☆Rendezvous (リトライ☆ランデヴー)",
				"artist" => "Nyaa-tan (Rie Murakawa)"]],
		"Ending 1a" => [
			"file" => "Ending1a-Etotama.webm",
			"song" => [
				"title" => "blue moment",
				"artist" => "ソルラルBOB"]],
		"Ending 1b" => [
			"file" => "Ending1b-Etotama.webm",
			"song" => [
				"title" => "blue moment",
				"artist" => "ソルラルBOB"]],
		"Ending 1c" => [
			"file" => "Ending1c-Etotama.webm",
			"song" => [
				"title" => "blue moment",
				"artist" => "ソルラルBOB"]],
		"Ending 1d" => [
			"file" => "Ending1d-Etotama.webm",
			"song" => [
				"title" => "blue moment",
				"artist" => "ソルラルBOB"]],
		"Ending 1k" => [
			"file" => "Ending1k-Etotama.webm",
			"song" => [
				"title" => "blue moment",
				"artist" => "ソルラルBOB"]],
		"Ending 1l" => [
			"file" => "Ending1l-Etotama.webm",
			"song" => [
				"title" => "blue moment",
				"artist" => "ソルラルBOB"]]],
	"Eureka Seven" => [
		"Opening 1" => [
			"file" => "Opening1-EurekaSeven.webm"],
		"Opening 2" => [
			"file" => "Opening2-EurekaSeven.webm"],
		"Opening 3" => [
			"file" => "Opening3-EurekaSeven.webm"],
		"Opening 4" => [
			"file" => "Opening4-EurekaSeven.webm"],
		"Ending 1" => [
			"file" => "Ending1-EurekaSeven.webm"],
		"Ending 2" => [
			"file" => "Ending2-EurekaSeven.webm"],
		"Ending 3" => [
			"file" => "Ending3-EurekaSeven.webm"],
		"Ending 4" => [
			"file" => "Ending4-EurekaSeven.webm"]],
	"Eureka Seven AO" => [
		"Opening 1a" => [
			"file" => "Opening1a-EurekaSevenAO.webm"],
		"Opening 1b" => [
			"file" => "Opening1b-EurekaSevenAO.webm"],
		"Opening 1c" => [
			"file" => "Opening1c-EurekaSevenAO.webm"],
		"Ending 1a" => [
			"file" => "Ending1a-EurekaSevenAO.webm"],
		"Ending 1b" => [
			"file" => "Ending1b-EurekaSevenAO.webm"],
		"Ending 1c" => [
			"file" => "Ending1c-EurekaSevenAO.webm"],
		"Ending 2" => [
			"file" => "Ending2-EurekaSevenAO.webm"]],
	"Fairy Tail" => [
		"Opening 1" => [
			"file" => "Opening1-FairyTail.webm"],
		"Opening 2" => [
			"file" => "Opening2-FairyTail.webm"],
		"Opening 3" => [
			"file" => "Opening3-FairyTail.webm"],
		"Opening 4" => [
			"file" => "Opening4-FairyTail.webm"],
		"Opening 5" => [
			"file" => "Opening5-FairyTail.webm"],
		"Opening 6" => [
			"file" => "Opening6-FairyTail.webm"],
		"Opening 7" => [
			"file" => "Opening7-FairyTail.webm"],
		"Opening 8" => [
			"file" => "Opening8-FairyTail.webm"],
		"Opening 9" => [
			"file" => "Opening9-FairyTail.webm"],
		"Opening 11" => [
			"file" => "Opening11-FairyTail.webm"],
		"Opening 13" => [
			"file" => "Opening13-FairyTail.webm"],
		"Opening 14" => [
			"file" => "Opening14-FairyTail.webm"],
		"Ending 1" => [
			"file" => "Ending1-FairyTail.webm"],
		"Ending 2" => [
			"file" => "Ending2-FairyTail.webm"],
		"Ending 3" => [
			"file" => "Ending3-FairyTail.webm"],
		"Ending 4" => [
			"file" => "Ending4-FairyTail.webm"],
		"Ending 5" => [
			"file" => "Ending5-FairyTail.webm"],
		"Ending 6" => [
			"file" => "Ending6-FairyTail.webm"],
		"Ending 7" => [
			"file" => "Ending7-FairyTail.webm"],
		"Ending 8" => [
			"file" => "Ending8-FairyTail.webm"],
		"Ending 9" => [
			"file" => "Ending9-FairyTail.webm"],
		"Ending 10" => [
			"file" => "Ending10-FairyTail.webm"],
		"Ending 12" => [
			"file" => "Ending12-FairyTail.webm"],
		"Ending 13" => [
			"file" => "Ending13-FairyTail.webm"],
		"Ending 14" => [
			"file" => "Ending14-FairyTail.webm"]],
	"Fate/kaleid liner Prisma Illya" => [
		"Opening 1" => [
			"file" => "Opening1-FateKaleidLinerPrismaIllya.webm"],
		"Ending 1" => [
			"file" => "Ending1-FateKaleidLinerPrismaIllya.webm"],
		"Ending 2" => [
			"file" => "Ending2-FateKaleidLinerPrismaIllya.webm"]],
	"Fate/kaleid liner Prisma Illya 2wei!" => [
		"Opening 1" => [
			"file" => "Opening1-FateKaleidLinerPrismaIllyaZwei!.webm"],
		"Ending 1" => [
			"file" => "Ending1-FateKaleidLinerPrismaIllyaZwei!.webm"]],
	"Fate/stay night: Unlimited Blade Works" => [
		"Opening 1" => [
			"file" => "Opening1-FateStayNightUBW.webm"],
		"Opening 2" => [
			"file" => "Opening2-FateStayNightUBW.webm"],
		"Ending 1" => [
			"file" => "Ending1-FateStayNightUBW.webm"]],
	"Fate/Zero" => [
		"Opening 1" => [
			"file" => "Opening1-FateZero.webm"],
		"Opening 2" => [
			"file" => "Opening2-FateZero.webm"],
		"Ending 1" => [
			"file" => "Ending1-FateZero.webm"],
		"Ending 2" => [
			"file" => "Ending2-FateZero.webm"]],
	"Flag" => [
		"Opening 1" => [
			"file" => "Opening1-Flag.webm"]],
	"Free!" => [
		"Opening 1" => [
			"file" => "Opening1-Free!.webm"],
		"Ending 1" => [
			"file" => "Ending1-Free!.webm"]],
	"Fullmetal Alchemist: Brotherhood" => [
		"Opening 1" => [
			"file" => "Opening1-FullmetalAlchemistBrotherhood.webm"],
		"Opening 2" => [
			"file" => "Opening2-FullmetalAlchemistBrotherhood.webm"],
		"Opening 3" => [
			"file" => "Opening3-FullmetalAlchemistBrotherhood.webm"],
		"Opening 4" => [
			"file" => "Opening4-FullmetalAlchemistBrotherhood.webm"],
		"Opening 5" => [
			"file" => "Opening5-FullmetalAlchemistBrotherhood.webm"],
		"Ending 1" => [
			"file" => "Ending1-FullmetalAlchemistBrotherhood.webm"],
		"Ending 2" => [
			"file" => "Ending2-FullmetalAlchemistBrotherhood.webm"],
		"Ending 3" => [
			"file" => "Ending3-FullmetalAlchemistBrotherhood.webm"],
		"Ending 4" => [
			"file" => "Ending4-FullmetalAlchemistBrotherhood.webm"],
		"Ending 5" => [
			"file" => "Ending5-FullmetalAlchemistBrotherhood.webm"]],
	"Futakoi Alternative" => [
		"Opening 1" => [
			"file" => "Opening1-FutakoiAlternative.webm"],
		"Ending 1" => [
			"file" => "Ending1-FutakoiAlternative.webm"],
		"Ending 2" => [
			"file" => "Ending2-FutakoiAlternative.webm"],
		"Ending 3" => [
			"file" => "Ending3-FutakoiAlternative.webm"]],
	"Futsuu no Joshikousei ga [Locodol] Yatte Mita." => [
		"Opening 1" => [
			"file" => "Opening1-FutsuuNoJoshikouseiGaLocodolYattemita.webm"]],
	"GANGSTA." => [
		"Opening 1" => [
			"file" => "Opening1-GANGSTA.webm",
			"song" => [
				"title" => "Renegade",
				"artist" => "STEREO DIVE FOUNDATION"]]],
	"GATE" => [
		"Opening 1" => [
			"file" => "Opening1-GATE.webm"],
		"Ending 1" => [
			"file" => "Ending1-GATE.webm"]],
	"Gekkan Shoujo Nozaki-kun" => [
		"Opening 1" => [
			"file" => "Opening1-GekkanShoujoNozakiKun.webm"],
		"Ending 1" => [
			"file" => "Ending1-GekkanShoujoNozakiKun.webm"]],
	"Gintama" => [
		"Opening 1" => [
			"file" => "Opening1-Gintama.webm"],
		"Opening 2" => [
			"file" => "Opening2-Gintama.webm"],
		"Opening 3" => [
			"file" => "Opening3-Gintama.webm"],
		"Opening 4" => [
			"file" => "Opening4-Gintama.webm"],
		"Opening 5" => [
			"file" => "Opening5-Gintama.webm"],
		"Opening 6" => [
			"file" => "Opening6-Gintama.webm"],
		"Opening 7" => [
			"file" => "Opening7-Gintama.webm"],
		"Opening 8" => [
			"file" => "Opening8-Gintama.webm"]],
	"Girls Und Panzer" => [
		"Opening 1" => [
			"file" => "Opening1-GirlsUndPanzer.webm",
			"song" => [
				"title" => "DreamRiser",
				"artist" => "Choucho"]],
		"Ending 1" => [
			"file" => "Ending1-GirlsUndPanzer.webm",
			"song" => [
				"title" => "DreamRiser",
				"artist" => "Choucho"]],
		"Ending 2" => [
			"file" => "Ending2-GirlsUndPanzer.webm",
			"song" => [
				"title" => "Enter Enter MISSION!",
				"artist" => "Ankou Team (あんこうチーム)"]]],
	"Glasslip" => [
		"Opening 1" => [
			"file" => "Opening1-Glasslip.webm"],
		"Ending 1" => [
			"file" => "Ending1-Glasslip.webm"]],
	"Gokukoku no Brynhildr" => [
		"Opening 1" => [
			"file" => "Opening1-GokukokuNoBrynhildr.webm"],
		"Opening 2" => [
			"file" => "Opening2-GokukokuNoBrynhildr.webm"]],
	"Goku Sayonara Zetsubou Sensei" => [
		"Opening 1" => [
			"file" => "Opening1-GokuSayonaraZetsubouSensei.webm"],
		"Opening 2" => [
			"file" => "Opening2-GokuSayonaraZetsubouSensei.webm"],
		"Opening 3" => [
			"file" => "Opening3-GokuSayonaraZetsubouSensei.webm"]],
	"Golden Time" => [
		"Opening 1" => [
			"file" => "Opening1-GoldenTime.webm"],
		"Opening 2" => [
			"file" => "Opening2-GoldenTime.webm"],
		"Ending 1" => [
			"file" => "Ending1-GoldenTime.webm"],
		"Ending 2" => [
			"file" => "Ending2-GoldenTime.webm"]],
	"Gosick" => [
		"Opening 1" => [
			"file" => "Opening1-Gosick.webm",
			"song" => [
				"title" => "Destin Histoire",
				"artist" => "yoshiki*lisa (吉木りさ)"]],
		"Ending 1" => [
			"file" => "Ending1-Gosick.webm",
			"song" => [
				"title" => "Resuscitated Hope",
				"artist" => "Lisa Komine"]],
		"Ending 2" => [
			"file" => "Ending2-Gosick.webm",
			"song" => [
				"title" => "unity",
				"artist" => "Lisa Komine"]]],
	"Hacka Doll the Animation" => [
		"Opening 1" => [
			"file" => "Opening1-HackaDollTheAnimation.webm",
			"song" => [
				"title" => "Touch Tap Baby",
				"artist" => "Kaya Okuno, Miyu Takagi, & Nanami Yamashita"]]],
	"Guilty Crown" => [
		"Opening 1" => [
			"file" => "Opening1-GuiltyCrown.webm"],
		"Opening 2" => [
			"file" => "Opening2-GuiltyCrown.webm"],
		"Ending 1" => [
			"file" => "Ending1-GuiltyCrown.webm"]],
	"Haibane Renmei" => [
		"Opening 1" => [
			"file" => "Opening1-HaibaneRenmei.webm"],
		"Ending 1" => [
			"file" => "Ending1-HaibaneRenmei.webm"]],
	"Haiyore! Nyaruko-san" => [
		"Opening 1" => [
			"file" => "Opening1-HaiyoreNyarukoSan.webm"],
		"Ending 1" => [
			"file" => "Ending1-HaiyoreNyarukoSan.webm"]],
	"Haiyore! Nyaruko-san W" => [
		"Opening 1" => [
			"file" => "Opening1-HaiyoreNyarukoSanW.webm"],
		"Ending 1" => [
			"file" => "Ending1-HaiyoreNyarukoSanW.webm"],
		"Ending 2" => [
			"file" => "Ending2-HaiyoreNyarukoSanW.webm"],
		"Ending 3" => [
			"file" => "Ending3-HaiyoreNyarukoSanW.webm"],
		"Ending 4" => [
			"file" => "Ending4-HaiyoreNyarukoSanW.webm"],
		"Ending 5 (Kamen Rider)" => [
			"file" => "Ending5-HaiyoreNyarukoSanW.webm"],
		"Ending 6 (Kamen Rider)" => [
			"file" => "Ending6-HaiyoreNyarukoSanW.webm"],
		"Ending 7" => [
			"file" => "Ending7-HaiyoreNyarukoSanW.webm"]],
	"Haiyore! Nyaruko-san F" => [
		"Opening 1" => [
			"file" => "Opening1-HaiyoreNyarukoSanF.webm"],
		"Ending 1" => [
			"file" => "Ending1-HaiyoreNyarukoSanF.webm"]],
	"Hamatora The Animation" => [
		"Opening 1" => [
			"file" => "Opening1-Hamatora.webm"]],
	"Hanasaku Iroha" => [
		"Opening 1" => [
			"file" => "Opening1-HanasakuIroha.webm"],
		"Opening 2" => [
			"file" => "Opening2-HanasakuIroha.webm"],
		"Ending 1" => [
			"file" => "Ending1-HanasakuIroha.webm"],
		"Ending 2" => [
			"file" => "Ending2-HanasakuIroha.webm"]],
	"Henneko (Hentai Ouji to Warawanai Neko)" => [
		"Opening 1" => [
			"file" => "Opening1-Henneko.webm"],
		"Ending 1" => [
			"file" => "Ending1-Henneko.webm"]],
	"Hibike! Euphonium" => [
		"Opening 1" => [
			"file" => "Opening1-Hibike!Euphonium.webm"],
		"Ending 1" => [
			"file" => "Ending1-Hibike!Euphonium.webm"],
		"Ending 2" => [
			"file" => "Ending2-Hibike!Euphonium.webm",
			"song" => [
				"title" => "愛を見つけた場所 (Ai wo Mitsuketa Basho)",
				"artist" => "奥 華子 (Oku Hanako)"]],
		"Ending 3" => [
			"file" => "Ending3-Hibike!Euphonium.webm"]],
	"Hidamari Sketch" => [
		"Opening 1" => [
			"file" => "Opening1-HidamariSketch.webm"],
		"Opening 2" => [
			"file" => "Opening2-HidamariSketch.webm"],
		"Opening 3" => [
			"file" => "Opening3-HidamariSketch.webm"],
		"Ending 1" => [
			"file" => "Ending1-HidamariSketch.webm"]],
	"Hidamari Sketch × 365" => [
		"Ending 1" => [
			"file" => "Ending1-HidamariSketchx365.webm"]],
	"Hidamari Sketch × Honeycomb" => [
		"Ending 1" => [
			"file" => "Ending1-HidamariSketchHoneycomb.webm"]],
	"Highschool DxD" => [
		"Ending 1" => [
			"file" => "Ending1-HighschoolDxD.webm"]],
	"Highschool DxD New" => [
		"Ending 1" => [
			"file" => "Ending1-HighschoolDxDNew.webm"],
		"Ending 2" => [
			"file" => "Ending2-HighschoolDxDNew.webm"]],
	"Higurashi kira" => [
		"Opening 1" => [
			"file" => "Opening1-HigurashiKira.webm"],
		"Ending 1" => [
			"file" => "Ending1-HigurashiKira.webm"]],
	"Hitsugi no Chaika" => [
		"Opening 1" => [
			"file" => "Opening1-HitsugiNoChaika.webm"]],
	"Hyouka" => [
		"Opening 1" => [
			"file" => "Opening1-Hyouka.webm",
			"song" => [
				"title" => "Yasashisa no Riyū (優しさの理由 Reason of Kindness)",
				"artist" => "ChouCho"]],
		"Opening 2" => [
			"file" => "Opening2-Hyouka.webm",
			"song" => [
				"title" => "Mikansei Stride (未完成ストライド Unfinished Stride)",
				"artist" => "Saori Kodama"]],
		"Ending 1" => [
			"file" => "Ending1-Hyouka.webm",
			"song" => [
				"title" => "Madoromi no Yakusoku (まどろみの約束 Promise of Slumber)",
				"artist" => "Satomi Sato and Ai Kayano"]],
		"Ending 2" => [
			"file" => "Ending2-Hyouka.webm",
			"song" => [
				"title" => "Kimi ni Matsuwaru Mystery (君にまつわるミステリー Mystery Surrounding You)",
				"artist" => "Satomi Sato and Ai Kayano"]]],
	"Hyperdimension Neptunia Re;Birth 1" => [
		"Game Opening 1" => [
			"file" => "Opening1-HyperdimensionNeptuniaReBirth1.webm",
			"song" => [
				"title" => "Miracle! Portable☆Mission",
				"artist" => "nao"]],
		"Game Ending 1" => [
			"file" => "Ending1-HyperdimensionNeptuniaReBirth1.webm"]],
	"The Idolmaster (iDOLM@STER)" => [
		"Opening 1" => [
			"file" => "Opening1-Idolmaster.webm"],
		"Opening 2" => [
			"file" => "Opening2-Idolmaster.webm"]],
	"Inari, Konkon, Koi Iroha" => [
		"Opening 1" => [
			"file" => "Opening1-InariKonkonKoiIroha.webm"],
		"Ending 1" => [
			"file" => "Ending1-InariKonkonKoiIroha.webm"]],
	"Jewelpet Tinkle" => [
		"Opening 1a" => [
			"file" => "Opening1a-JewelpetTinkle.webm"],
		"Opening 1b" => [
			"file" => "Opening1b-JewelpetTinkle.webm"],
		"Opening 1c" => [
			"file" => "Opening1c-JewelpetTinkle.webm"],
		"Ending 1a" => [
			"file" => "Ending1a-JewelpetTinkle.webm"],
		"Ending 1c" => [
			"file" => "Ending1c-JewelpetTinkle.webm"]],
	"Jinrui wa Suitai Shimashita" => [
		"Opening 1" => [
			"file" => "Opening1-JinruiWaSuitaiShimashita.webm"],
		"Ending 1" => [
			"file" => "Ending1-JinruiWaSuitaiShimashita.webm"]],
	"JoJo's Bizarre Adventure (2012)" => [
		"Opening 1" => [
			"file" => "Opening1-JoJo2012.webm"],
		"Opening 2" => [
			"file" => "Opening2-JoJo2012.webm"]],
	"K-On!" => [
		"Opening 1a" => [
			"file" => "Opening1a-K-On!.webm"],
		"Opening 1b" => [
			"file" => "Opening1b-K-On!.webm"],
		"Ending 1" => [
			"file" => "Ending1-K-On!.webm"]],
	"K-On!!" => [
		"Opening 1" => [
			"file" => "Opening1-K-On!!.webm"],
		"Opening 2" => [
			"file" => "Opening2-K-On!!.webm"],
		"Ending 1" => [
			"file" => "Ending1-K-On!!.webm"],
		"Ending 2" => [
			"file" => "Ending2-K-On!!.webm"]],
	"K-On! Movie" => [
		"Opening 1" => [
			"file" => "Opening1-K-On!Movie.webm"],
		"Ending 1" => [
			"file" => "Ending1-K-On!Movie.webm"]],
	"Kakumeiki Valvrave" => [
		"Opening 1a" => [
			"file" => "Opening1a-KakumeikiValvrave.webm"],
		"Opening 1b" => [
			"file" => "Opening1b-KakumeikiValvrave.webm"],
		"Ending 1" => [
			"file" => "Ending1-KakumeikiValvrave.webm"],
		"Ending 2" => [
			"file" => "Ending2-KakumeikiValvrave.webm"]],
	"Kamisama Dolls" => [
		"Opening 1" => [
			"file" => "Opening1-KamisamaDolls.webm"],
		"Ending 1" => [
			"file" => "Ending1-KamisamaDolls.webm"]],
	"Kanon (2006)" => [
		"Opening 1" => [
			"file" => "Opening1-Kanon(2006).webm"],
		"Ending 1" => [
			"file" => "Ending1-Kanon(2006).webm"]],
	"Kantai Collection: KanColle" => [
		"Opening 1" => [
			"file" => "Opening1-KantaiCollection.webm"],
		"Ending 1" => [
			"file" => "Ending1-KantaiCollection.webm"]],
	"Katanagatari" => [
		"Opening 1" => [
			"file" => "Opening1-Katanagatari.webm"],
		"Opening 2" => [
			"file" => "Opening2-Katanagatari.webm"],
		"Ending 1" => [
			"file" => "Ending1-Katanagatari.webm"],
		"Ending 2" => [
			"file" => "Ending2-Katanagatari.webm"],
		"Ending 3" => [
			"file" => "Ending3-Katanagatari.webm"],
		"Ending 4" => [
			"file" => "Ending4-Katanagatari.webm"],
		"Ending 5" => [
			"file" => "Ending5-Katanagatari.webm"],
		"Ending 6" => [
			"file" => "Ending6-Katanagatari.webm"],
		"Ending 7" => [
			"file" => "Ending7-Katanagatari.webm"],
		"Ending 8" => [
			"file" => "Ending8-Katanagatari.webm"],
		"Ending 9" => [
			"file" => "Ending9-Katanagatari.webm"],
		"Ending 10" => [
			"file" => "Ending10-Katanagatari.webm"],
		"Ending 11" => [
			"file" => "Ending11-Katanagatari.webm"]],
	"Kill la Kill" => [
		"Opening 1" => [
			"file" => "Opening1-KillLaKill.webm"],
		"Opening 2" => [
			"file" => "Opening2-KillLaKill.webm"]],
	"Kiss X Sis" => [
		"Opening 1" => [
			"file" => "Opening1-KissXSis.webm"],
		"Ending 1" => [
			"file" => "Ending1-KissXSis.webm"],
		"Ending 2" => [
			"file" => "Ending2-KissXSis.webm"]],
	"Kitakubu Katsudou Kiroku" => [
		"Opening 1" => [
			"file" => "Opening1-KitakubuKatsudouKiroku.webm"],
		"Ending 1" => [
			"file" => "Ending1-KitakubuKatsudouKiroku.webm"],
		"Ending 2" => [
			"file" => "Ending2-KitakubuKatsudouKiroku.webm"],
		"Ending 3" => [
			"file" => "Ending3-KitakubuKatsudouKiroku.webm"]],
	"Kokoro Connect" => [
		"Opening 1" => [
			"file" => "Opening1-KokoroConnect.webm"],
		"Opening 1 (TV)" => [
			"file" => "Opening1TV-KokoroConnect.webm"],
		"Ending 1" => [
			"file" => "Ending1-KokoroConnect.webm"],
		"Ending 2" => [
			"file" => "Ending2-KokoroConnect.webm"],
		"Ending 3" => [
			"file" => "Ending3-KokoroConnect.webm"]],
	"Kokoro Connect: Michi Random" => [
		"Opening 1" => [
			"file" => "Opening1-KokoroConnectMichiRandom.webm"],
		"Ending 1" => [
			"file" => "Ending1-KokoroConnectMichiRandom.webm"]],
	"Kuragehime" => [
		"Opening 1" => [
			"file" => "Opening1-Kuragehime.webm"],
		"Ending 1" => [
			"file" => "Ending1-Kuragehime.webm"]],
	"Kurenai" => [
		"Opening 1" => [
			"file" => "Opening1-Kurenai.webm"],
		"Ending 1" => [
			"file" => "Ending1-Kurenai.webm"]],
	"Log Horizon" => [
		"Opening 1" => [
			"file" => "Opening1-LogHorizon.webm"],
		"Ending 1" => [
			"file" => "Ending1-LogHorizon.webm"]],
	"Log Horizon 2" => [
		"Opening 1" => [
			"file" => "Opening1-LogHorizon2.webm"],
		"Ending 1" => [
			"file" => "Ending1-LogHorizon2.webm"]],
	"Love Live!" => [
		"Opening 1" => [
			"file" => "Opening1-LoveLive!.webm"]],
	"Love Live! S2" => [
		"Opening 1" => [
			"file" => "Opening1-LoveLive!S2.webm"]],
	"Lucky Star" => [
		"Opening 1" => [
			"file" => "Opening1-LuckyStar.webm"]],
	"Machine-Doll wa Kizutsunai (Unbreakable Machine-Doll)" => [
		"Opening 1" => [
			"file" => "Opening1-MachinedollWaKizutsukanai.webm"],
		"Ending 1" => [
			"file" => "Ending1-MachinedollWaKizutsukanai.webm"]],
	"Mahou Shoujo Madoka Magica" => [
		"Opening 1" => [
			"file" => "Opening1-MadokaMagica.webm"]],
	"Maria Holic" => [
		"Opening 1" => [
			"file" => "Opening1-MariaHolic.webm"],
		"Ending 1" => [
			"file" => "Ending1-MariaHolic.webm"]],
	"Mawaru Penguindrum" => [
		"Opening 1" => [
			"file" => "Opening1-MawaruPenguindrum.webm"],
		"Opening 2" => [
			"file" => "Opening2-MawaruPenguindrum.webm"],
		"Ending 1" => [
			"file" => "Ending1-MawaruPenguindrum.webm"],
		"Ending 2" => [
			"file" => "Ending2-MawaruPenguindrum.webm"],
		"Ending 3" => [
			"file" => "Ending3-MawaruPenguindrum.webm"],
		"Ending 4" => [
			"file" => "Ending4-MawaruPenguindrum.webm"],
		"Ending 5" => [
			"file" => "Ending5-MawaruPenguindrum.webm"],
		"Ending 6" => [
			"file" => "Ending6-MawaruPenguindrum.webm"],
		"Ending 7" => [
			"file" => "Ending7-MawaruPenguindrum.webm"],
		"Ending 8" => [
			"file" => "Ending8-MawaruPenguindrum.webm"]],
	"Mayo Chiki" => [
		"Opening 1" => [
			"file" => "Opening1-MayoChiki.webm"],
		"Ending 1" => [
			"file" => "Ending1-MayoChiki.webm"]],
	"Mayoi Neko Overrun!" => [
		"Opening 1" => [
			"file" => "Opening1-MayoiNekoOverrun!.webm"],
		"Opening 2" => [
			"file" => "Opening2-MayoiNekoOverrun!.webm"],
		"Ending 1a" => [
			"file" => "Ending1a-MayoiNekoOverrun!.webm"],
		"Ending 1b" => [
			"file" => "Ending1b-MayoiNekoOverrun!.webm"],
		"Ending 2" => [
			"file" => "Ending2-MayoiNekoOverrun!.webm"],
		"Ending 3" => [
			"file" => "Ending3-MayoiNekoOverrun!.webm"],
		"Ending 4" => [
			"file" => "Ending4-MayoiNekoOverrun!.webm"]],
	"Mekakucity Actors" => [
		"Opening 1" => [
			"file" => "Opening1-MekakucityActors.webm"],
		"Ending 1" => [
			"file" => "Ending1-MekakucityActors.webm"]],
	"Mikagura Gakuen Kumikyoku" => [
		"Opening 1" => [
			"file" => "Opening1-MikaguraGakuenKumikyoku.webm"]],
	"Mirai Nikki" => [
		"Opening 1" => [
			"file" => "Opening1-MiraiNikki.webm"],
		"Opening 2" => [
			"file" => "Opening2-MiraiNikki.webm"],
		"Opening 3" => [
			"file" => "Opening3-MiraiNikki.webm"],
		"Ending 1" => [
			"file" => "Ending1-MiraiNikki.webm"],
		"Ending 2" => [
			"file" => "Ending2-MiraiNikki.webm"],
		"Ending 3" => [
			"file" => "Ending3-MiraiNikki.webm"]],
	"MM!" => [
		"Opening 1" => [
			"file" => "Opening1-MM!.webm"],
		"Ending 1" => [
			"file" => "Ending1-MM!.webm"]],
	"Mobile Suit Gundam" => [
		"Opening 1" => [
			"file" => "Opening1-MobileSuitGundam.webm"],
		"Ending 1" => [
			"file" => "Ending1-MobileSuitGundam.webm"]],
	"Mondaiji-tachi ga Isekai kara Kuru Sou Desu yo?" => [
		"Opening 1" => [
			"file" => "Opening1-MondaijiTachiGaIsekaiKaraKuruSouDesuYo.webm"],
		"Ending 1" => [
			"file" => "Ending1-MondaijiTachiGaIsekaiKaraKuruSouDesuYo.webm"]],
	"Monogatari Series: Second Season" => [
		"Nekomonogatari (Shiro) Opening" => [
			"file" => "Opening1-MonogatariSeriesSecondSeason.webm"],
		"Kabukimonogatari Opening" => [
			"file" => "Opening2-MonogatariSeriesSecondSeason.webm"],
		"Otorimonogatari TV Opening" => [
			"file" => "Opening3TV-MonogatariSeriesSecondSeason.webm",
			"song" => [
				"title" => "Delusion♥Express (もうそう♥えくすぷれす)",
				"artist" => "Kana Hanazawa"]],
		"Otorimonogatari Opening" => [
			"file" => "Opening3-MonogatariSeriesSecondSeason.webm",
			"song" => [
				"title" => "Delusion♥Express (もうそう♥えくすぷれす)",
				"artist" => "Kana Hanazawa"]],
		"Onimonogatari Opening" => [
			"file" => "Opening4-MonogatariSeriesSecondSeason.webm"],
		"Koimonogatari Opening a" => [
			"file" => "Opening5-MonogatariSeriesSecondSeason.webm"],
		"Koimonogatari Opening b" => [
			"file" => "Opening6-MonogatariSeriesSecondSeason.webm"],
		"Hanamonogatari Opening" => [
			"file" => "Opening7-MonogatariSeriesSecondSeason.webm"],
		"Nekomonogatari (Shiro) Ending a" => [
			"file" => "Ending1-MonogatariSeriesSecondSeason.webm"],
		"Nekomonogatari (Shiro) Ending b" => [
			"file" => "Ending2-MonogatariSeriesSecondSeason.webm"],
		"Kabukimonogatari Ending" => [
			"file" => "Ending3-MonogatariSeriesSecondSeason.webm"],
		"Otorimonogatari Ending" => [
			"file" => "Ending4-MonogatariSeriesSecondSeason.webm"],
		"Onimonogatari Ending" => [
			"file" => "Ending5-MonogatariSeriesSecondSeason.webm"],
		"Koimonogatari Ending" => [
			"file" => "Ending6-MonogatariSeriesSecondSeason.webm"],
		"Hanamonogatari Ending" => [
			"file" => "Ending7-MonogatariSeriesSecondSeason.webm"]],
	"Monster Musume" => [
		"Opening 1" => [
			"file" => "Opening1-MonsterMusume.webm"],
		"Ending 1" => [
			"file" => "Ending1-MonsterMusume.webm"]],
	"Nadia: The Secret Of Blue Water" => [
		"Opening 1a" => [
			"file" => "Opening1a-NadiaTheSecretOfBlueWater.webm"],
		"Opening 1b" => [
			"file" => "Opening1b-NadiaTheSecretOfBlueWater.webm"],
		"Ending 1" => [
			"file" => "Ending1-NadiaTheSecretOfBlueWater.webm"]],
	"Nagi no Asukara" => [
		"Opening 1" => [
			"file" => "Opening1-NagiNoAsukara.webm"],
		"Opening 2" => [
			"file" => "Opening2-NagiNoAsukara.webm"],
		"Ending 1" => [
			"file" => "Ending1-NagiNoAsukara.webm"],
		"Ending 2" => [
			"file" => "Ending2-NagiNoAsukara.webm"]],
	"NEEDLESS" => [
		"Opening 1" => [
			"file" => "Opening1-NEEDLESS.webm"],
		"Opening 2" => [
			"file" => "Opening2-NEEDLESS.webm"],
		"Ending 1" => [
			"file" => "Ending1-NEEDLESS.webm"],
		"Ending 2" => [
			"file" => "Ending2-NEEDLESS.webm"]],
	"Nekomonogatari (Kuro): Tsubasa Family" => [
		"Opening 1" => [
			"file" => "Opening1-NekomonogatariKuro.webm",
			"song" => [
				"title" => "perfect slumbers",
				"artist" => "Yui Horie"],
			"subtitles" => "Commie"],
		"Ending 1a" => [
			"file" => "Ending1a-NekomonogatariKuro.webm",
			"song" => [
				"title" => "Kieru Daydream (消えるdaydream)",
				"artist" => "Marina Kawano"]],
		"Ending 1b" => [
			"file" => "Ending1b-NekomonogatariKuro.webm"]],
	"Neon Genesis Evangelion" => [
		"Opening 1" => [
			"file" => "Opening1-NeonGenesisEvangelion.webm"],
		"Ending 1" => [
			"file" => "Ending1-NeonGenesisEvangelion.webm"]],
	"Nichijou" => [
		"Opening 1" => [
			"file" => "Opening1-Nichijou.webm"],
		"Opening 2" => [
			"file" => "Opening2-Nichijou.webm"],
		"Ending 1" => [
			"file" => "Ending1-Nichijou.webm"],
		"Ending 2" => [
			"file" => "Ending2-Nichijou.webm"],
		"Ending 3" => [
			"file" => "Ending3-Nichijou.webm"],
		"Ending 4" => [
			"file" => "Ending4-Nichijou.webm"],
		"Ending 5" => [
			"file" => "Ending5-Nichijou.webm"],
		"Ending 6" => [
			"file" => "Ending6-Nichijou.webm"],
		"Ending 7" => [
			"file" => "Ending7-Nichijou.webm"],
		"Ending 8" => [
			"file" => "Ending8-Nichijou.webm"],
		"Ending 10" => [
			"file" => "Ending10-Nichijou.webm"],
		"Ending 12" => [
			"file" => "Ending12-Nichijou.webm"],
		"Ending 13" => [
			"file" => "Ending13-Nichijou.webm"],
		"Ending 14" => [
			"file" => "Ending14-Nichijou.webm"]],
	"Nisekoi" => [
		"Opening 1" => [
			"file" => "Opening1-Nisekoi.webm"],
		"Ending 1" => [
			"file" => "Ending1-Nisekoi.webm"],
		"Ending 2" => [
			"file" => "Ending2-Nisekoi.webm"],
		"Ending 3" => [
			"file" => "Ending3-Nisekoi.webm"],
		"Ending 4" => [
			"file" => "Ending4-Nisekoi.webm"],
		"Ending 5" => [
			"file" => "Ending5-Nisekoi.webm"],
		"Ending 6" => [
			"file" => "Ending6-Nisekoi.webm"],
		"Ending 7" => [
			"file" => "Ending7-Nisekoi.webm"]],
	"Nisemonogatari" => [
		"Karen Bee Opening 1a" => [
			"file" => "Opening1a-Nisemonogatari.webm"],
		"Karen Bee Opening 1b" => [
			"file" => "Opening1b-Nisemonogatari.webm"],
		"Karen Bee Opening 2" => [
			"file" => "Opening2-Nisemonogatari.webm"],
		"Tsukihi Pheonix Opening" => [
			"file" => "Opening3-Nisemonogatari.webm"],
		"Karen Bee Ending a" => [
			"file" => "Ending1a-Nisemonogatari.webm"],
		"Karen Bee Ending b" => [
			"file" => "Ending1b-Nisemonogatari.webm"],
		"Tsukihi Pheonix Ending" => [
			"file" => "Ending1c-Nisemonogatari.webm"]],
	"Nobunagun" => [
		"Opening 1" => [
			"file" => "Opening1-Nobunagun.webm"]],
	"No Game No Life" => [
		"Opening 1" => [
			"file" => "Opening1-NoGameNoLife.webm"],
		"Ending 1" => [
			"file" => "Ending1-NoGameNoLife.webm"]],
	"Non Non Biyori" => [
		"Opening 1" => [
			"file" => "Opening1-NonNonBiyori.webm"],
		"Ending 1" => [
			"file" => "Ending1-NonNonBiyori.webm"],
		"Ending 2" => [
			"file" => "Ending2-NonNonBiyori.webm"]],
	"Noragami" => [
		"Opening 1a" => [
			"file" => "Opening1a-Noragami.webm"],
		"Opening 1b" => [
			"file" => "Opening1b-Noragami.webm"],
		"Ending 1" => [
			"file" => "Ending1-Noragami.webm"]],
	"Noragami Aragoto" => [
		"Opening 1" => [
			"file" => "Opening1-NoragamiAragoto.webm"]],
	"Okitegami Kyoko no Biboroku" => [
		"Opening 1e" => [
			"file" => "Opening1e-OkitegamiKyokoNoBiboroku.webm",
			"song" => [
				"title" => "Overflowing Things",
				"artist" => "Goodbye Holiday"]]],
	"Okusama ga Seitokaichou!" => [
		"Opening 1" => [
			"file" => "Opening1-OkusamaGaSeitokaichou!.webm"]],
	"One Punch Man" => [
		"Opening 1" => [
			"file" => "Opening1-OnePunchMan.webm"]],
	"Ore no Imouto ga Konnani Kawaii Wake ga Nai (Oreimo) / Stardust Witch Meruru" => [
		"Oreimo Opening 1" => [
			"file" => "Opening1-Oreimo.webm"],
		"Stardust Witch Meruru Opening 1" => [
			"file" => "Opening1-StardustWitchMeruru.webm"],
		"Stardust Witch Meruru Opening 2" => [
			"file" => "Opening2-StardustWitchMeruru.webm"]],
	"Oreshura" => [
		"Opening 1" => [
			"file" => "Opening1-Oreshura.webm"],
		"Ending 1" => [
			"file" => "Ending1-Oreshura.webm"]],
	"Outbreak Company" => [
		"Opening 1" => [
			"file" => "Opening1-OutbreakCompany.webm"],
		"Ending 1" => [
			"file" => "Ending1-OutbreakCompany.webm"]],
	"Overlord" => [
		"Opening 1" => [
			"file" => "Opening1-Overlord.webm"],
		"Ending 1" => [
			"file" => "Ending1-Overlord.webm"]],
	"Owarimonogatari" => [
		"Opening 1 (Ougi Formula)" => [
			"file" => "Opening1-Owarimonogatari.webm",
			"song" => [
				"title" => "Decent Black",
				"artist" => "Meg Rock"]],
		"Opening 2 (Sodachi Riddle and Sodachi Lost)" => [
			"file" => "Opening2-Owarimonogatari.webm",
			"song" => [
				"title" => "mathemagics (老倉育)",
				"artist" => "Inoue Marina (井上麻里奈)"]],
		"Opening 3 (Shinobu Mail)" => [
			"file" => "Opening3-Owarimonogatari.webm",
			"song" => [
				"title" => "mein Schatz",
				"artist" => "unknown"]],
		"Ending 1a (Ougi Formula, Sodachi Riddle, and Sodachi Lost)" => [
			"file" => "Ending1a-Owarimonogatari.webm",
			"song" => [
				"title" => "Sayonara no Yukue (さよならのゆくえ)",
				"artist" => "Alisa Takigawa"]],
		"Ending 1b (Shinobu Mail)" => [
			"file" => "Ending1b-Owarimonogatari.webm",
			"song" => [
				"title" => "Sayonara no Yukue (さよならのゆくえ)",
				"artist" => "Alisa Takigawa"]]],
	"PaniPoni Dash!" => [
		"Opening 1" => [
			"file" => "Opening1-PaniPoniDash.webm"],
		"Opening 2" => [
			"file" => "Opening2-PaniPoniDash.webm"],
		"Opening 3" => [
			"file" => "Opening3-PaniPoniDash.webm"]],
	"Papa no Iu Koto o Kikinasai!" => [
		"Opening 1a" => [
			"file" => "Opening1a-PapaNoIuKotoOKikinasai!.webm"],
		"Opening 1b" => [
			"file" => "Opening1b-PapaNoIuKotoOKikinasai!.webm"],
		"Ending 1" => [
			"file" => "Ending1-PapaNoIuKotoOKikinasai!.webm"]],
	"Paprika" => [
		"Opening 1" => [
			"file" => "Opening1-Paprika.webm"]],
	"Parasyte" => [
		"Opening 1" => [
			"file" => "Opening1-Parasyte.webm",
			"subtitles" => "VCB-Studio+Underwater"]],
	"Persona 3 FES" => [
		"Game Opening 1" => [
			"file" => "Opening1-Persona3FES.webm",
			"song" => [
				"title" => "Burn My Dread",
				"artist" => "Yumi Kawamura"]],
		"Game Opening 2" => [
			"file" => "Opening2-Persona3FES.webm",
			"song" => [
				"title" => "P3 fes",
				"artist" => "Yumi Kawamura feat. Lotus Juice"]]],
	"Persona 4: The Animation" => [
		"Opening 1" => [
			"file" => "Opening1-Persona4TheAnimation.webm"],
		"Ending 1" => [
			"file" => "Ending1-Persona4TheAnimation.webm"]],
	"Planetes" => [
		"Opening 1" => [
			"file" => "Opening1-Planetes.webm"],
		"Ending 1" => [
			"file" => "Ending1-Planetes.webm"]],
	"Plastic Memories" => [
		"Opening 1d" => [
			"file" => "Opening1d-PlasticMemories.webm",
			"song" => [
				"title" => "Ring of Fortune",
				"artist" => "Eri Sasaki (佐々木恵梨)"]],
		"Opening 1e" => [
			"file" => "Opening1e-PlasticMemories.webm",
			"song" => [
				"title" => "Ring of Fortune",
				"artist" => "Eri Sasaki (佐々木恵梨)"]],
		"Ending 1" => [
			"file" => "Ending1-PlasticMemories.webm",
			"song" => [
				"title" => "Asayake no Starmine (朝焼けのスターマイン)",
				"artist" => "Asami Imai"]]],
	"Psycho Pass" => [
		"Opening 1" => [
			"file" => "Opening1-PsychoPass.webm"],
		"Opening 2" => [
			"file" => "Opening2-PsychoPass.webm"],
		"Ending 1" => [
			"file" => "Ending1-PsychoPass.webm"],
		"Ending 2" => [
			"file" => "Ending2-PsychoPass.webm"]],
	"Psycho Pass 2" => [
		"Opening 1" => [
			"file" => "Opening1-PsychoPass2.webm"],
		"Ending 1" => [
			"file" => "Ending1-PsychoPass2.webm"]],
	"Ranpo Kitan: Game of Laplace" => [
		"Opening 1" => [
			"file" => "Opening1-RanpoKitanGameOfLaplace.webm",
			"song" => [
				"title" => "Speed to Masatsu",
				"artist" => "Amazarashi"]]],
	"Rinne no Lagrange: Flower Declaration of Your Heart - Season 2" => [
		"Opening 1" => [
			"file" => "Opening1-RinneNoLagrangeFlowerDeclarationOfYourHeartSeason2.webm"],
		"Ending 1a" => [
			"file" => "Ending1a-RinneNoLagrangeFlowerDeclarationOfYourHeartSeason2.webm"],
		"Ending 1b" => [
			"file" => "Ending1b-RinneNoLagrangeFlowerDeclarationOfYourHeartSeason2.webm"],
		"Ending 1c" => [
			"file" => "Ending1c-RinneNoLagrangeFlowerDeclarationOfYourHeartSeason2.webm"],
		"Ending 2" => [
			"file" => "Ending2-RinneNoLagrangeFlowerDeclarationOfYourHeartSeason2.webm"]],
	"Rokka no Yuusha" => [
		"Opening 1" => [
			"file" => "Opening1-RokkaNoYuusha.webm"],
		"Ending 1" => [
			"file" => "Ending1-RokkaNoYuusha.webm"]],
	"Rokujouma no Shinryakusha!?" => [
		"Opening 1" => [
			"file" => "Opening1-RokujoumaNoShinryakusha.webm",
			"song" => [
				"title" => "Koukan win-win Mujouken (好感win-win無条件)",
				"artist" => "Heart♥Invader (ハート♥インベーダー)"]],
		"Ending 1" => [
			"file" => "Ending1-RokujoumaNoShinryakusha.webm",
			"song" => [
				"title" => "Koi wa Milk Tea (恋はみるくてぃ)",
				"artist" => "petit milady"]]],
	"Rosario + Vampire Capu2" => [
		"Opening 1" => [
			"file" => "Opening1-RosarioToVampireCapu2.webm"]],
	"Sakamichi no Apollon" => [
		"Opening 1" => [
			"file" => "Opening1-SakamichiNoApollon.webm"],
		"Ending 1" => [
			"file" => "Ending1-SakamichiNoApollon.webm"]],
	"Sakurasou no Pet na Kanojo" => [
		"Opening 1" => [
			"file" => "Opening1-SakurasouNoPetNaKanojo.webm"],
		"Opening 2" => [
			"file" => "Opening2-SakurasouNoPetNaKanojo.webm"],
		"Ending 1" => [
			"file" => "Ending1-SakurasouNoPetNaKanojo.webm"],
		"Ending 2" => [
			"file" => "Ending2-SakurasouNoPetNaKanojo.webm"]],
	"Sakura Trick" => [
		"Opening 1" => [
			"file" => "Opening1-SakuraTrick.webm"],
		"Ending 1" => [
			"file" => "Ending1-SakuraTrick.webm"]],
	"Samurai Champloo" => [
		"Opening 1" => [
			"file" => "Opening1-SamuraiChamploo.webm"],
		"Ending 1" => [
			"file" => "Ending1-SamuraiChamploo.webm"]],
	"Sayonara Zetsubou Sensei" => [
		"Opening 1" => [
			"file" => "Opening1-SayonaraZetsubouSensei.webm"],
		"Ending 1" => [
			"file" => "Ending1-SayonaraZetsubouSensei.webm"]],
	"Seikoku no Dragonar" => [
		"Opening 1" => [
			"file" => "Opening1-SeikokuNoDragonar.webm"],
		"Opening 2" => [
			"file" => "Opening2-SeikokuNoDragonar.webm"],
		"Ending 1" => [
			"file" => "Ending1-SeikokuNoDragonar.webm"]],
	"Seirei Tsukai no Blade Dance" => [
		"Opening 1" => [
			"file" => "Opening1-SeireiTsukaiNoBladeDance.webm"],
		"Ending 1" => [
			"file" => "Ending1-SeireiTsukaiNoBladeDance.webm"]],
	"Serial Experiments Lain" => [
		"Opening 1" => [
			"file" => "Opening1-SerialExperimentsLain.webm"]],
	"Shakugan no Shana" => [
		"Opening 2" => [
			"file" => "Opening2-ShakuganNoShana.webm"],
		"Ending 1" => [
			"file" => "Ending1-ShakuganNoShana.webm"],
		"Ending 2" => [
			"file" => "Ending2-ShakuganNoShana.webm"]],
	"Shakugan no Shana Final" => [
		"Opening 2" => [
			"file" => "Opening2-ShakuganNoShanaFinal.webm"]],
	"Shakugan no Shana Second" => [
		"Ending 1" => [
			"file" => "Ending1-ShakuganNoShanaSecond.webm"],
		"Ending 2" => [
			"file" => "Ending2-ShakuganNoShanaSecond.webm"]],
	"Shigatsu wa Kimi no Uso (Your lie in April)" => [
		"Opening 1" => [
			"file" => "Opening1-ShigatsuWaKimiNoUso.webm"],
		"Ending 1" => [
			"file" => "Ending1-ShigatsuWaKimiNoUso.webm"]],
	"Shingeki no Bahamut Genesis (Rage of Bahamut: Genesis)" => [
		"Opening 1" => [
			"file" => "Opening1-ShingekiNoBahamut.webm"],
		"Ending 1" => [
			"file" => "Ending1-ShingekiNoBahamut.webm"]],
	"Shinmai Maou no Testament" => [
		"Opening 1" => [
			"file" => "Opening1-ShinmaiMaouNoTestament.webm"]],
	"Shinsekai yori (From the New World)" => [
		"Ending 1" => [
			"file" => "Ending1-ShinsekaiYori.webm"],
		"Ending 2" => [
			"file" => "Ending2-ShinsekaiYori.webm"]],
	"Shirobako" => [
		"Opening 1" => [
			"file" => "Opening1-Shirobako.webm"]],
	"Sidonia no Kishi (Knights of Sidonia)" => [
		"Opening 1" => [
			"file" => "Opening1-SidoniaNoKishi.webm"],
		"Ending 1" => [
			"file" => "Ending1-SidoniaNoKishi.webm"]],
	"Soul Eater" => [
		"Opening 1" => [
			"file" => "Opening1-SoulEater.webm",
			"song" => [
				"title" => "Resonance",
				"artist" => "T.M.Revolution"]],
		"Opening 2" => [
			"file" => "Opening2-SoulEater.webm",
			"song" => [
				"title" => "PAPERMOON",
				"artist" => "Tommy heavenly6"]],
		"Ending 1" => [
			"file" => "Ending1-SoulEater.webm",
			"song" => [
				"title" => "I Wanna Be",
				"artist" => "STANCE PUNKS"]],
		"Ending 2a" => [
			"file" => "Ending2a-SoulEater.webm",
			"song" => [
				"title" => "Style",
				"artist" => "Kana Nishino"]],
		"Ending 2b" => [
			"file" => "Ending2b-SoulEater.webm",
			"song" => [
				"title" => "Style",
				"artist" => "Kana Nishino"]],
		"Ending 3" => [
			"file" => "Ending3-SoulEater.webm",
			"song" => [
				"title" => "Bakusou Yumeuta",
				"artist" => "Diggy-MO'"]],
		"Ending 4" => [
			"file" => "Ending4-SoulEater.webm",
			"song" => [
				"title" => "Strength",
				"artist" => "abingdon boys school"]]],
	"Space☆Dandy" => [
		"Ending 1" => [
			"file" => "Ending1-SpaceDandy.webm"]],
	"Spice and Wolf" => [
		"Opening 1" => [
			"file" => "Opening1-SpiceAndWolf.webm"],
		"Ending 1" => [
			"file" => "Ending1-SpiceAndWolf.webm"]],
	"Spice and Wolf II" => [
		"Opening 1" => [
			"file" => "Opening1-SpiceAndWolf2.webm"],
		"Ending 1" => [
			"file" => "Ending1-SpiceAndWolf2.webm"]],
	"Steins;Gate" => [
		"Opening 1" => [
			"file" => "Opening1-SteinsGate.webm"],
		"Ending 1" => [
			"file" => "Ending1-SteinsGate.webm"]],
	"Strike The Blood" => [
		"Opening 1" => [
			"file" => "Opening1-StrikeTheBlood.webm",
			"song" => [
				"title" => "Strike the Blood (ストライク・ザ・ブラッド)",
				"artist" => "Kishida Kyoudan & The Akeboshi Rockets"]],
		"Opening 2a" => [
			"file" => "Opening2a-StrikeTheBlood.webm",
			"song" => [
				"title" => "Fight 4 Real",
				"artist" => "ALTIMA"]],
		"Opening 2b" => [
			"file" => "Opening2b-StrikeTheBlood.webm",
			"song" => [
				"title" => "Fight 4 Real",
				"artist" => "ALTIMA"]],
		"Ending 1" => [
			"file" => "Ending1-StrikeTheBlood.webm",
			"song" => [
				"title" => "Strike My Soul",
				"artist" => "Yuka Iguchi"]],
		"Ending 2" => [
			"file" => "Ending2-StrikeTheBlood.webm",
			"song" => [
				"title" => "signal",
				"artist" => "Kanon Wakeshima"]]],
	"Strike Witches" => [
		"Opening 1" => [
			"file" => "Opening1-StrikeWitches.webm"],
		"Ending 1" => [
			"file" => "Ending1-StrikeWitches.webm"],
		"Ending 2" => [
			"file" => "Ending2-StrikeWitches.webm"],
		"Ending 3" => [
			"file" => "Ending3-StrikeWitches.webm"],
		"Ending 4" => [
			"file" => "Ending4-StrikeWitches.webm"],
		"Ending 5" => [
			"file" => "Ending5-StrikeWitches.webm"],
		"Ending 6" => [
			"file" => "Ending6-StrikeWitches.webm"],
		"Ending 7" => [
			"file" => "Ending7-StrikeWitches.webm"],
		"Ending 8" => [
			"file" => "Ending8-StrikeWitches.webm"],
		"Ending 9" => [
			"file" => "Ending9-StrikeWitches.webm"],
		"Ending 10" => [
			"file" => "Ending10-StrikeWitches.webm"]],
	"Strike Witches 2" => [
		"Opening 1" => [
			"file" => "Opening1-StrikeWitches2.webm"],
		"Opening 2" => [
			"file" => "Opening2-StrikeWitches2.webm"],
		"Ending 1" => [
			"file" => "Ending1-StrikeWitches2.webm"],
		"Ending 2" => [
			"file" => "Ending2-StrikeWitches2.webm"],
		"Ending 3" => [
			"file" => "Ending3-StrikeWitches2.webm"],
		"Ending 4" => [
			"file" => "Ending4-StrikeWitches2.webm"],
		"Ending 5" => [
			"file" => "Ending5-StrikeWitches2.webm"],
		"Ending 6" => [
			"file" => "Ending6-StrikeWitches2.webm"],
		"Ending 7" => [
			"file" => "Ending7-StrikeWitches2.webm"],
		"Ending 8" => [
			"file" => "Ending8-StrikeWitches2.webm"],
		"Ending 9" => [
			"file" => "Ending9-StrikeWitches2.webm"],
		"Ending 10" => [
			"file" => "Ending10-StrikeWitches2.webm"],
		"Ending 11" => [
			"file" => "Ending11-StrikeWitches2.webm"],
		"Ending 12" => [
			"file" => "Ending12-StrikeWitches2.webm"]],
	"Strike Witches: Operation Victory Arrow" => [
		"Opening 1" => [
			"file" => "Opening1-StrikeWitches3.webm"],
		"Ending 1" => [
			"file" => "Ending1-StrikeWitches3.webm"],
		"Ending 2" => [
			"file" => "Ending2-StrikeWitches3.webm"],
		"Ending 3" => [
			"file" => "Ending3-StrikeWitches3.webm"]],
	"Suisei no Gargantia" => [
		"Opening 1" => [
			"file" => "Opening1-SuiseiNoGargantia.webm"],
		"Ending 1" => [
			"file" => "Ending1-SuiseiNoGargantia.webm"]],
	"Sukitte Ii na yo." => [
		"Opening 1" => [
			"file" => "Opening1-SukitteIiNaYo.webm"],
		"Ending 1" => [
			"file" => "Ending1-SukitteIiNaYo.webm"]],
	"Super Danganronpa 2" => [
		"Game Opening" => [
			"file" => "Opening1-SuperDanganronpa2.webm"]],
	"Sword Art Online" => [
		"Opening 1" => [
			"file" => "Opening1-SwordArtOnline.webm",
			"song" => [
				"title" => "crossing field",
				"artist" => "LiSA"]],
		"Opening 2" => [
			"file" => "Opening2-SwordArtOnline.webm",
			"song" => [
				"title" => "INNOCENCE",
				"artist" => "藍井エイル (Aoi Eir)"]],
		"Ending 1" => [
			"file" => "Ending1-SwordArtOnline.webm",
			"song" => [
				"title" => "ユメセカイ (Yume Sekai)",
				"artist" => "戸松 遥 (Haruka Tomatsu)"]],
		"Ending 2" => [
			"file" => "Ending2-SwordArtOnline.webm",
			"song" => [
				"title" => "Overfly",
				"artist" => "春奈るな (Haruna Luna)"]]],
	"Sword Art Online 2" => [
		"Opening 1" => [
			"file" => "Opening1-SwordArtOnline2.webm",
			"song" => [
				"title" => "IGNITE",
				"artist" => "藍井エイル (Aoi Eir)"]],
		"Opening 2a" => [
			"file" => "Opening2a-SwordArtOnline2.webm"],
		"Opening 2b" => [
			"file" => "Opening2b-SwordArtOnline2.webm"],
		"Ending 1" => [
			"file" => "Ending1-SwordArtOnline2.webm"],
		"Ending 2" => [
			"file" => "Ending2-SwordArtOnline2.webm"],
		"Ending 3a" => [
			"file" => "Ending3a-SwordArtOnline2.webm"],
		"Ending 3b" => [
			"file" => "Ending3b-SwordArtOnline2.webm"]],
	"Tales of Graces ƒ" => [
		"Game opening" => [
			"file" => "Opening1-TalesOfGracesF.webm"]],
	"Tales Of Symphonia" => [
		"Game opening (Gamecube)" => [
			"file" => "OpeningGC-TalesOfSymphonia.webm"],
		"Game opening (Playstation 2)" => [
			"file" => "OpeningPS2-TalesOfSymphonia.webm"]],
	"Tales Of Symphonia: Dawn of the New World" => [
		"Game opening" => [
			"file" => "Opening1-TalesOfSymphoniaDawnOfTheNewWorld.webm"]],
	"Tales Of Xillia" => [
		"Game opening (Jude)" => [
			"file" => "OpeningJude-TalesOfXillia.webm"],
		"Game opening (Milla)" => [
			"file" => "OpeningMilla-TalesOfXillia.webm"]],
	"Tales Of Xillia 2" => [
		"Game opening" => [
			"file" => "Opening1-TalesOfXillia2.webm"]],
	"Tamako Love Story" => [
		"Opening 1" => [
			"file" => "Opening1-TamakoLoveStory.webm"]],
	"Tamako Market" => [
		"Opening 1" => [
			"file" => "Opening1-TamakoMarket.webm"],
		"Ending 1" => [
			"file" => "Ending1-TamakoMarket.webm"]],
	"Tari Tari" => [
		"Opening 1" => [
			"file" => "Opening1-TariTari.webm"],
		"Ending 1" => [
			"file" => "Ending1-TariTari.webm"]],
	"Teekyuu" => [
		"Opening 1" => [
			"file" => "Opening1-Teekyuu.webm"]],
	"Teekyuu 2" => [
		"Opening 1a" => [
			"file" => "Opening1a-Teekyuu2.webm"],
		"Opening 1b" => [
			"file" => "Opening1b-Teekyuu2.webm"]],
	"Teekyuu 3" => [
		"Opening 1" => [
			"file" => "Opening1-Teekyuu3.webm"],
		"Opening 2" => [
			"file" => "Opening2-Teekyuu3.webm"]],
	"Teekyuu 4" => [
		"Opening 1" => [
			"file" => "Opening1-Teekyuu4.webm"]],
	"Tengen Toppa Gurren Lagann" => [
		"Opening 1a" => [
			"file" => "Opening1a-TengenToppaGurrenLagann.webm"],
		"Opening 1c" => [
			"file" => "Opening1c-TengenToppaGurrenLagann.webm"],
		"Ending 1a" => [
			"file" => "Ending1a-TengenToppaGurrenLagann.webm"],
		"Ending 1b" => [
			"file" => "Ending1b-TengenToppaGurrenLagann.webm"],
		"Ending 2" => [
			"file" => "Ending2-TengenToppaGurrenLagann.webm"]],
	"The Legend of Black Heaven" => [
		"Opening 1" => [
			"file" => "Opening1-TheLegendofBlackHeaven.webm"]],
	"The Melancholy of Haruhi Suzumiya" => [
		"Opening 1" => [
			"file" => "Opening1-TheMelancholyOfHaruhiSuzumiya.webm"],
		"Ending 1" => [
			"file" => "Ending1-TheMelancholyOfHaruhiSuzumiya.webm"],
		"TV Ending 1" => [
			"file" => "Ending1TV-TheMelancholyOfHaruhiSuzumiya.webm"]],
	"The Super Dimension Fortress Macross" => [
		"Opening 1" => [
			"file" => "Opening1-Macross.webm"]],
	"The Tatami Galaxy" => [
		"Opening 1" => [
			"file" => "Opening1-TatamiGalaxy.webm"],
		"Ending 1" => [
			"file" => "Ending1-TatamiGalaxy.webm"]],
	"Toaru Kagaku no Railgun (A Certain Scientific Railgun)" => [
		"Opening 1" => [
			"file" => "Opening1-ToaruKagakuNoRailgun.webm"],
		"Opening 2" => [
			"file" => "Opening2-ToaruKagakuNoRailgun.webm"],
		"Ending 1" => [
			"file" => "Ending1-ToaruKagakuNoRailgun.webm"],
		"Ending 2" => [
			"file" => "Ending2-ToaruKagakuNoRailgun.webm"]],
	"Toaru Kagaku no Railgun S (A Certain Scientific Railgun 2nd Season)" => [
		"Opening 1" => [
			"file" => "Opening1-ToaruKagakuNoRailgunS.webm"],
		"Opening 2" => [
			"file" => "Opening2-ToaruKagakuNoRailgunS.webm"]],
	"Toaru Majutsu no Index (A Certain Magical Index)" => [
		"Opening 1" => [
			"file" => "Opening1-ToaruMajutsuNoIndex.webm"],
		"Opening 2" => [
			"file" => "Opening2-ToaruMajutsuNoIndex.webm"],
		"Ending 1" => [
			"file" => "Ending1-ToaruMajutsuNoIndex.webm"],
		"Ending 2" => [
			"file" => "Ending2-ToaruMajutsuNoIndex.webm"]],
	"Toaru Majutsu no Index II (A Certain Magical Index 2)" => [
		"Opening 1" => [
			"file" => "Opening1-ToaruMajutsuNoIndexII.webm"],
		"Opening 2" => [
			"file" => "Opening2-ToaruMajutsuNoIndexII.webm"],
		"Ending 1" => [
			"file" => "Ending1-ToaruMajutsuNoIndexII.webm"],
		"Ending 2" => [
			"file" => "Ending2-ToaruMajutsuNoIndexII.webm"]],
	"Tokyo ESP" => [
		"Opening 1" => [
			"file" => "Opening1-TokyoESP.webm"],
		"Ending 1" => [
			"file" => "Ending1-TokyoESP.webm"]],
	"Tokyo Ghoul" => [
		"Opening 1" => [
			"file" => "Opening1-TokyoGhoul.webm",
			"song" => [
				"title" => "Unravel",
				"artist" => "TK from Ling Tosite Sigure"]],
		"Ending 1a" => [
			"file" => "Ending1a-TokyoGhoul.webm"],
		"Ending 1b" => [
			"file" => "Ending1b-TokyoGhoul.webm"],
		"Ending 1c" => [
			"file" => "Ending1c-TokyoGhoul.webm"],
		"Ending 1d" => [
			"file" => "Ending1d-TokyoGhoul.webm"],
		"Ending 1e" => [
			"file" => "Ending1e-TokyoGhoul.webm"],
		"Ending 1f" => [
			"file" => "Ending1f-TokyoGhoul.webm"]],
	"Tokyo Ghoul √A" => [
		"Opening 1" => [
			"file" => "Opening1-TokyoGhoulRootA.webm"]],
	"Tonari no Kaibutsu" => [
		"Opening 1" => [
			"file" => "Opening1-TonariNoKaibutsu.webm"]],
	"Toradora" => [
		"Opening 1" => [
			"file" => "Opening1-Toradora.webm",
			"song" => [
				"title" => "Pre-parade",
				"artist" => "Rie Kugimiya, Yui Horie, and Eri Kitamura"]],
		"Opening 2" => [
			"file" => "Opening2-Toradora.webm"],
		"Ending 1" => [
			"file" => "Ending1-Toradora.webm"],
		"Ending 2" => [
			"file" => "Ending2-Toradora.webm"]],
	"True Tears" => [
		"Opening 1" => [
			"file" => "Opening1-TrueTears.webm"]],
	"Tsukimonogatari: Yotsugi Doll" => [
		"Opening 1" => [
			"file" => "Opening1-Tsukimonogatari.webm"],
		"Ending 1" => [
			"file" => "Ending1-Tsukimonogatari.webm"]],
	"Tsuritama" => [
		"Opening 1" => [
			"file" => "Opening1-Tsuritama.webm"],
		"Ending 1" => [
			"file" => "Ending1-Tsuritama.webm"]],
	"Uchuu no Stellvia" => [
		"Opening 1" => [
			"file" => "Opening1-UchuuNoStellvia.webm"],
		"Opening 2" => [
			"file" => "Opening2-UchuuNoStellvia.webm"]],
	"Umineko no Naku Koro ni" => [
		"Opening 1" => [
			"file" => "Opening1-UminekoNoNakuKoroNi.webm",
			"song" => [
				"title" => "One-winged Bird",
				"artist" => "Shikata Akiko"]],
		"Ending 1" => [
			"file" => "Ending1-UminekoNoNakuKoroNi.webm",
			"song" => [
				"title" => "la divina tragedia ~Makyoku~",
				"artist" => "Jimang"]]],
	"Watamote" => [
		"Opening 1" => [
			"file" => "Opening1-Watamote.webm"]],
	"Welcome to the NHK (NHK ni Youkoso!)" => [
		"Opening 1" => [
			"file" => "Opening1-WelcomeToTheNHK.webm"],
		"Ending 1" => [
			"file" => "Ending1-WelcomeToTheNHK.webm"],
		"Ending 2" => [
			"file" => "Ending2-WelcomeToTheNHK.webm"]],
	"Welcome to the NHK (NHK ni Youkoso!) / Puru Puru Pururin" => [
		"Opening 1" => [
			"file" => "Opening1-WelcomeToTheNHKPururin.webm"]],
	"Witch Craft Works" => [
		"Opening 1" => [
			"file" => "Opening1-WitchCraftWorks.webm",
			"song" => [
				"title" => "divine intervention",
				"artist" => "fhána"]],
		"Ending 1a" => [
			"file" => "Ending1a-WitchCraftWorks.webm",
			"song" => [
				"title" => "Witch☆Activity (ウィッチ☆アクティビティ)",
				"artist" => "KMM Gang (ＫＭＭ団)"]],
		"Ending 1b" => [
			"file" => "Ending1b-WitchCraftWorks.webm",
			"song" => [
				"title" => "Witch☆Activity (ウィッチ☆アクティビティ)",
				"artist" => "KMM Gang (ＫＭＭ団)"]],
		"Ending 1c" => [
			"file" => "Ending1c-WitchCraftWorks.webm",
			"song" => [
				"title" => "Witch☆Activity (ウィッチ☆アクティビティ)",
				"artist" => "KMM Gang (ＫＭＭ団)"]],
		"Ending 1d" => [
			"file" => "Ending1d-WitchCraftWorks.webm",
			"song" => [
				"title" => "Witch☆Activity (ウィッチ☆アクティビティ)",
				"artist" => "KMM Gang (ＫＭＭ団)"]],
		"Ending 1e" => [
			"file" => "Ending1e-WitchCraftWorks.webm",
			"song" => [
				"title" => "Witch☆Activity (ウィッチ☆アクティビティ)",
				"artist" => "KMM Gang (ＫＭＭ団)"]],
		"Ending 1f" => [
			"file" => "Ending1f-WitchCraftWorks.webm",
			"song" => [
				"title" => "Witch☆Activity (ウィッチ☆アクティビティ)",
				"artist" => "KMM Gang (ＫＭＭ団)"]],
		"Ending 1g" => [
			"file" => "Ending1g-WitchCraftWorks.webm",
			"song" => [
				"title" => "Witch☆Activity (ウィッチ☆アクティビティ)",
				"artist" => "KMM Gang (ＫＭＭ団)"]],
		"Ending 1h" => [
			"file" => "Ending1h-WitchCraftWorks.webm",
			"song" => [
				"title" => "Witch☆Activity (ウィッチ☆アクティビティ)",
				"artist" => "KMM Gang (ＫＭＭ団)"]],
		"Ending 1i" => [
			"file" => "Ending1i-WitchCraftWorks.webm",
			"song" => [
				"title" => "Witch☆Activity (ウィッチ☆アクティビティ)",
				"artist" => "KMM Gang (ＫＭＭ団)"]],
		"Ending 1j" => [
			"file" => "Ending1j-WitchCraftWorks.webm",
			"song" => [
				"title" => "Witch☆Activity (ウィッチ☆アクティビティ)",
				"artist" => "KMM Gang (ＫＭＭ団)"]],
		"Ending 1k" => [
			"file" => "Ending1k-WitchCraftWorks.webm",
			"song" => [
				"title" => "Witch☆Activity (ウィッチ☆アクティビティ)",
				"artist" => "KMM Gang (ＫＭＭ団)"]],
		"Ending 1l" => [
			"file" => "Ending1l-WitchCraftWorks.webm",
			"song" => [
				"title" => "Witch☆Activity (ウィッチ☆アクティビティ)",
				"artist" => "KMM Gang (ＫＭＭ団)"]]],
	"Xam'd: Lost memories" => [
		"Opening 1" => [
			"file" => "Opening1-Xamd.webm"],
		"Opening 2" => [
			"file" => "Opening2-Xamd.webm"],
		"Ending 1" => [
			"file" => "Ending1-Xamd.webm"],
		"Ending 2" => [
			"file" => "Ending2-Xamd.webm"],
		"Ending 3" => [
			"file" => "Ending3-Xamd.webm"]],
	"Yahari Ore no Seishun Lovecome wa Machigatte Iru." => [
		"Opening 1" => [
			"file" => "Opening1-YahariOreNoSeishunLovecomeWaMachigatteIru.webm"],
		"Ending 1" => [
			"file" => "Ending1-YahariOreNoSeishunLovecomeWaMachigatteIru.webm"],
		"Ending 2" => [
			"file" => "Ending2-YahariOreNoSeishunLovecomeWaMachigatteIru.webm"]],
	"Yondemasu yo, Azazel-san. Z" => [
		"Opening 1" => [
			"file" => "Opening1-Yondemasuyo,AzazelSanZ.webm"],
		"Ending 1" => [
			"file" => "Ending1-Yondemasuyo,AzazelSanZ.webm"],
		"Ending 2" => [
			"file" => "Ending2-Yondemasuyo,AzazelSanZ.webm"],
		"Ending 3" => [
			"file" => "Ending3-Yondemasuyo,AzazelSanZ.webm"]],
	"Yurikuma Arashi" => [
		"Opening 1" => [
			"file" => "Opening1-YurikumaArashi.webm"],
		"Ending 1" => [
			"file" => "Ending1-YurikumaArashi.webm"]],
	"Yuru Yuri" => [
		"Opening 1" => [
			"file" => "Opening1-YuruYuri.webm"],
		"Ending 1" => [
			"file" => "Ending1-YuruYuri.webm"]],
	"Yuru Yuri 2" => [
		"Opening 1" => [
			"file" => "Opening1-YuruYuri2.webm",
			"song" => [
				"title" => "Yes! YuYuYu☆YuruYuri♪♪ (いぇす！ゆゆゆ☆ゆるゆり♪♪)",
				"artist" => "Shiori Mikami, Yuka Ōtsubo, Minami Tsuda, and Rumi Ōkubo"],
			"subtitles" => "FFFansubs"],
		"Ending 1" => [
			"file" => "Ending1-YuruYuri2.webm",
			"song" => [
				"title" => "100% Chu~ Middle Schoolers (100%ちゅ～学生)",
				"artist" => "Shiori Mikami, Yuka Ōtsubo, Minami Tsuda, and Rumi Ōkubo"],
			"subtitles" => "FFFansubs"]],
	"Yuru Yuri Nachuyachumi!" => [
		"Opening 1" => [
			"file" => "Opening1-YuruYuriNachuyachumi!.webm"],
		"Ending 1" => [
			"file" => "Ending1-YuruYuriNachuyachumi!.webm"]],
	"Yuru Yuri San Hai!" => [
		"Opening 1 (Live Action Version)" => [
			"file" => "Opening1LiveAction-YuruYuriSanHai!.webm",
			"song" => [
				"title" => "Chochocho! Yuru Yuri☆Capriccio!!! (ちょちょちょ！ゆるゆり☆かぷりっちょ!!!)",
				"artist" => "Nanamori Chu☆Goraku Bu (七森中☆ごらく部)"]]],
	"Yuyushiki" => [
		"Opening 1" => [
			"file" => "Opening1-Yuyushiki.webm"],
		"Ending 1a" => [
			"file" => "Ending1a-Yuyushiki.webm"],
		"Ending 1b" => [
			"file" => "Ending1b-Yuyushiki.webm"],
		"Ending 1c" => [
			"file" => "Ending1c-Yuyushiki.webm"],
		"Ending 1d" => [
			"file" => "Ending1d-Yuyushiki.webm"],
		"Ending 1e" => [
			"file" => "Ending1e-Yuyushiki.webm"],
		"Ending 1f" => [
			"file" => "Ending1f-Yuyushiki.webm"],
		"Ending 1g" => [
			"file" => "Ending1g-Yuyushiki.webm"],
		"Ending 1h" => [
			"file" => "Ending1h-Yuyushiki.webm"],
		"Ending 1i" => [
			"file" => "Ending1i-Yuyushiki.webm"],
		"Ending 1j" => [
			"file" => "Ending1j-Yuyushiki.webm"],
		"Ending 1k" => [
			"file" => "Ending1k-Yuyushiki.webm"]],
	"Zankyou no Terror (Terror in Resonance)" => [
		"Opening 1" => [
			"file" => "Opening1-ZankyouNoTerror.webm",
			"song" => [
				"title" => "Trigger",
				"artist" => "Yuuki Ozaki (from Galileo Galilei)"]],
		"Ending 1" => [
			"file" => "Ending1-ZankyouNoTerror.webm",
			"song" => [
				"title" => "誰か、海を。 (Dare ka, Umi wo.)",
				"artist" => "Aimer"]]],
	"Zan Sayonara Zetsubou Sensei" => [
		"Opening 1" => [
			"file" => "Opening1-ZanSayonaraZetsubouSensei.webm"],
		"Ending 1" => [
			"file" => "Ending1-ZanSayonaraZetsubouSensei.webm"],
		"Ending 2" => [
			"file" => "Ending2-ZanSayonaraZetsubouSensei.webm"],
		"Ending 3" => [
			"file" => "Ending3-ZanSayonaraZetsubouSensei.webm"]],
	"Zan Sayonara Zetsubou Sensei Bangachi" => [
		"Opening 1" => [
			"file" => "Opening1-ZanSayonaraZetsubouSenseiBangachi.webm"]],
	"Zero no Tsukaima" => [
		"Opening 1" => [
			"file" => "Opening1-ZeroNoTsukaima.webm"],
		"Ending 1" => [
			"file" => "Ending1-ZeroNoTsukaima.webm"]],
	"Zero no Tsukaima: Futatsuki no Kishi" => [
		"Opening 1" => [
			"file" => "Opening1-ZeroNoTsukaimaSeason2.webm"],
		"Ending 1" => [
			"file" => "Ending1-ZeroNoTsukaimaSeason2.webm"]],
	"Zero no Tsukaima: Princess No Rondo" => [
		"Ending 1" => [
			"file" => "Ending1-ZeroNoTsukaimaPrincessNoRondo.webm"]],
	"Zoku Sayonara Zetsubou Sensei" => [
		"Opening 1" => [
			"file" => "Opening1-ZokuSayonaraZetsubouSensei.webm"],
		"Opening 2" => [
			"file" => "Opening2-ZokuSayonaraZetsubouSensei.webm"],
		"Ending 1" => [
			"file" => "Ending1-ZokuSayonaraZetsubouSensei.webm"],
		"Ending 2" => [
			"file" => "Ending2-ZokuSayonaraZetsubouSensei.webm"],
		"Ending 3" => [
			"file" => "Ending3-ZokuSayonaraZetsubouSensei.webm"],
		"Ending 4" => [
			"file" => "Ending4-ZokuSayonaraZetsubouSensei.webm"]]]
?>
