<?php
$names = array(
  "Opening1-AngelBeats.webm" => array(
    "title" => "Opening 1",
    "source" => "Angel Beats"),
  "Opening1-AoNoExorcist.webm" => array(
    "title" => "Opening 1",
    "source" => "Ao no Exorcist (Blue Exorcist)"),
  "Opening2-AoNoExorcist.webm" => array(
    "title" => "Opening 2",
    "source" => "Ao no Exorcist (Blue Exorcist)"),
    "Ending1-AoNoExorcist.webm" => array(
    "title" => "Ending 1",
    "source" => "Ao no Exorcist (Blue Exorcist)"),
  "Ending2-AoNoExorcist.webm" => array(
    "title" => "Ending 2",
    "source" => "Ao no Exorcist (Blue Exorcist)"),
  "Opening1-Bakemonogatari.webm" => array(
    "title" => "Opening 1",
    "source" => "Bakemonogatari"),
  "Opening1-BlackRockShooter.webm" => array(
    "title" => "Opening 1",
    "source" => "Black Rock Shooter"),
  "Opening1-BloodLad.webm" => array(
    "title" => "Opening 1",
    "source" => "Blood Lad"),
  "Ending1-BloodLad.webm" => array(
    "title" => "Ending 1",
    "source" => "Blood Lad"),
  "Opening1-CarnivalPhantasm.webm" => array(
    "title" => "Opening 1",
    "source" => "Carnival Phantasm"),
  "Opening1-Clannad.webm" => array(
    "title" => "Opening 1",
    "source" => "Clannad"),
  "Opening2-DanganronpaTheAnimation.webm" => array(
    "title" => "Opening 2",
    "source" => "Danganronpa: The animation"),
  "Opening1-DeadmanWonderland.webm" => array(
    "title" => "Opening 1",
    "source" => "Deadman Wonderland"),
  "Ending1-DeadmanWonderland.webm" => array(
    "title" => "Ending 1",
    "source" => "Deadman Wonderland"),
  "Opening1-DragonballKai.webm" => array(
    "title" => "Opening 1",
    "source" => "Dragon Ball Kai"),
  "Ending1-DragonballKai.webm" => array(
    "title" => "Ending 1",
    "source" => "Dragon Ball Kai"),
  "Ending2-DragonballKai.webm" => array(
    "title" => "Ending 2",
    "source" => "Dragon Ball Kai"),
  "Opening1-Durarara!!.webm" => array(
    "title" => "Opening 1",
    "source" => "Durarara!"),
  "Opening2-Durarara!!.webm" => array(
    "title" => "Opening 2",
    "source" => "Durarara!"),
  "Ending1-Durarara!!.webm" => array(
    "title" => "Ending 1",
    "source" => "Durarara!"),
  "Ending2-Durarara!!.webm" => array(
    "title" => "Ending 2",
    "source" => "Durarara!"),
  "Opening1-FateStayNightUBW.webm" => array(
    "title" => "Opening 1",
    "source" => "Fate/Stay night: Unlimited Blade Works"),
  "Opening2-FateStayNightUBW.webm" => array(
    "title" => "Opening 2",
    "source" => "Fate/Stay night: Unlimited Blade Works"),
  "Opening1-HaibaneRenmei.webm" => array(
    "title" => "Opening 1",
    "source" => "Haibane Renmei"),
  "Ending1-HaibaneRenmei.webm" => array(
    "title" => "Ending 1",
    "source" => "Haibane Renmei"),
  "Opening1-JoJo2012.webm" => array(
    "title" => "Opening 1",
    "source" => "JoJo's Bizarre adventure (2012)"),
  "Opening2-JoJo2012.webm" => array(
    "title" => "Opening 2",
    "source" => "JoJo's Bizarre adventure (2012)"),
  "Opening1-LogHorizon.webm" => array(
    "title" => "Opening 1",
    "source" => "Log Horizon"),
  "Ending1-LogHorizon.webm" => array(
    "title" => "Ending 1",
    "source" => "Log Horizon"),
  "Opening1-MayoChiki.webm" => array(
    "title" => "Opening 1",
    "source" => "Mayo Chiki"),
  "Ending1-MayoChiki.webm" => array(
    "title" => "Ending 1",
    "source" => "Mayo Chiki"),
  "Opening3-MiraiNikki.webm" => array(
    "title" => "Opening 3",
    "source" => "Mirai Nikki"),
  "Ending3-MiraiNikki.webm" => array(
    "title" => "Ending 3",
    "source" => "Mirai Nikki"),
  "Ending1-MM!.webm" => array(
    "title" => "Ending 1",
    "source" => "MM!"),
  "Opening3-MonogatariSeriesSecondSeason.webm" => array(
    "title" => "Opening 3",
    "source" => "Monogatari series second season"),
  "Opening1-Nisekoi.webm" => array(
    "title" => "Opening 1",
    "source" => "Nisekoi"),
  "Ending1-Nisekoi.webm" => array(
    "title" => "Ending 1",
    "source" => "Nisekoi"),
  "Opening1-Noragami.webm" => array(
    "title" => "Opening 1",
    "source" => "Noragami"),
  "Ending1-Noragami.webm" => array(
    "title" => "Ending 1",
    "source" => "Noragami"),
  "Opening1-PsychoPass2.webm" => array(
    "title" => "Opening 1",
    "source" => "Psycho Pass 2"),
  "Ending1-PsychoPass2.webm" => array(
    "title" => "Ending 1",
    "source" => "Psycho Pass 2"),
  "Opening1-StrikeTheBlood.webm" => array(
    "title" => "Opening 1",
    "source" => "Strike The Blood"),
  "Opening2-StrikeTheBlood.webm" => array(
    "title" => "Opening 2",
    "source" => "Strike The Blood"),
  "Ending1-StrikeTheBlood.webm" => array(
    "title" => "Ending 1",
    "source" => "Strike The Blood"),
  "Ending2-StrikeTheBlood.webm" => array(
    "title" => "Ending 2",
    "source" => "Strike The Blood"),
  "Opening-SuperDanganronpa2.webm" => array(
    "title" => "Game opening",
    "source" => "Super Danganronpa 2"),
  "Opening1-SwordArtOnline.webm" => array(
    "title" => "Opening 1",
    "source" => "Sword Art Online"),
  "Opening2-SwordArtOnline.webm" => array(
    "title" => "Opening 2",
    "source" => "Sword Art Online"),
  "Ending1-SwordArtOnline.webm" => array(
    "title" => "Ending 1",
    "source" => "Sword Art Online"),
  "Ending2-SwordArtOnline.webm" => array(
    "title" => "Ending 2",
    "source" => "Sword Art Online"),
  "Opening1-TalesOfXillia2.webm" => array(
    "title" => "Game opening",
    "source" => "Tales Of Xillia 2"),
  "Opening1-TokyoGhoul.webm" => array(
    "title" => "Opening 1",
    "source" => "Tokyo Ghoul"),
  "Opening1-TonariNoKaibutsu.webm" => array(
    "title" => "Opening 1",
    "source" => "Tonari no Kaibutsu"),
)
?>
