<?php
$names = array(
  "Opening1-AccelWorld.webm" => array(
    "title" => "Opening 1",
    "source" => "Accel World"),
  "Opening2-AccelWorld.webm" => array(
    "title" => "Opening 2",
    "source" => "Accel World"),
  "Ending1-AccelWorld.webm" => array(
    "title" => "Ending 1",
    "source" => "Accel World"),
  "Ending2-AccelWorld.webm" => array(
    "title" => "Ending 2",
    "source" => "Accel World"),
  "Opening1-AldnoahZero.webm" => array(
    "title" => "Opening 1",
    "source" => "Aldnoah Zero"),
  "Ending1-AldnoahZero.webm" => array(
    "title" => "Ending 1",
    "source" => "Aldnoah Zero"),
  "Opening1-AmagiBrilliantPark.webm" => array(
    "title" => "Opening 1",
    "source" => "Amagi Brilliant Park"),
  "Ending1-AmagiBrilliantPark.webm" => array(
    "title" => "Ending 1",
    "source" => "Amagi Brilliant Park"),
  "Opening1-AngelBeats.webm" => array(
    "title" => "Opening 1",
    "source" => "Angel Beats"),
  "Opening1-AoNoExorcist.webm" => array(
    "title" => "Opening 1",
    "source" => "Ao no Exorcist (Blue Exorcist)"),
  "Opening2-AoNoExorcist.webm" => array(
    "title" => "Opening 2",
    "source" => "Ao no Exorcist (Blue Exorcist)"),
    "Ending1-AoNoExorcist.webm" => array(
    "title" => "Ending 1",
    "source" => "Ao no Exorcist (Blue Exorcist)"),
  "Ending2-AoNoExorcist.webm" => array(
    "title" => "Ending 2",
    "source" => "Ao no Exorcist (Blue Exorcist)"),
  "Opening1-Bakemonogatari.webm" => array(
    "title" => "Opening 1",
    "source" => "Bakemonogatari"),
  "Opening1-Barakamon.webm" => array(
    "title" => "Opening 1",
    "source" => "Barakamon"),
  "Ending1-Barakamon.webm" => array(
    "title" => "Ending 1",
    "source" => "Barakamon"),
  "Opening1-BlackRockShooter.webm" => array(
    "title" => "Opening 1",
    "source" => "Black Rock Shooter"),
  "Opening1-BladeAndSoul.webm" => array(
    "title" => "Opening 1",
    "source" => "Blade and Soul"),
  "Opening1-BloodLad.webm" => array(
    "title" => "Opening 1",
    "source" => "Blood Lad"),
  "Ending1-BloodLad.webm" => array(
    "title" => "Ending 1",
    "source" => "Blood Lad"),
  "Opening1-BokuWaTomodachiGaSukunai.webm" => array(
    "title" => "Opening 1",
    "source" => "Boku wa Tomodachi ga Sukunai"),
  "Ending1-BokuWaTomodachiGaSukunai.webm" => array(
    "title" => "Ending 1",
    "source" => "Boku wa Tomodachi ga Sukunai"),
  "Opening1-CarnivalPhantasm.webm" => array(
    "title" => "Opening 1",
    "source" => "Carnival Phantasm"),
  "Opening1-CowboyBebop.webm" => array(
    "title" => "Opening 1",
    "source" => "Cowboy Bebop"),
  "Opening1-Clannad.webm" => array(
    "title" => "Opening 1",
    "source" => "Clannad"),
  "Opening2-DanganronpaTheAnimation.webm" => array(
    "title" => "Opening 2",
    "source" => "Danganronpa: The animation"),
  "Opening1-DeadmanWonderland.webm" => array(
    "title" => "Opening 1",
    "source" => "Deadman Wonderland"),
  "Ending1-DeadmanWonderland.webm" => array(
    "title" => "Ending 1",
    "source" => "Deadman Wonderland"),
  "Opening1-DeathParade.webm" => array(
    "title" => "Opening 1",
    "source" => "Death Parade"),
  "Opening1-DragonballKai.webm" => array(
    "title" => "Opening 1",
    "source" => "Dragon Ball Kai"),
  "Ending1-DragonballKai.webm" => array(
    "title" => "Ending 1",
    "source" => "Dragon Ball Kai"),
  "Ending2-DragonballKai.webm" => array(
    "title" => "Ending 2",
    "source" => "Dragon Ball Kai"),
  "Opening1-Durarara!!.webm" => array(
    "title" => "Opening 1",
    "source" => "Durarara!!"),
  "Opening2-Durarara!!.webm" => array(
    "title" => "Opening 2",
    "source" => "Durarara!!"),
  "Ending1-Durarara!!.webm" => array(
    "title" => "Ending 1",
    "source" => "Durarara!!"),
  "Ending2-Durarara!!.webm" => array(
    "title" => "Ending 2",
    "source" => "Durarara!!"),
  "Opening1-Durarara!!X2.webm" => array(
    "title" => "Opening 1",
    "source" => "Durarara!! X2"),
  "Ending1-Durarara!!X2.webm" => array(
    "title" => "Ending 1",
    "source" => "Durarara!! X2"),
  "Opening-DysfunctionalSystemsLearningToManageChaos.webm" => array(
    "title" => "Game Opening",
    "source" => "Dysfunctional Systems: Learning to manage chaos"),
  "Opening1-ErgoProxy.webm" => array(
    "title" => "Opening 1",
    "source" => "Ergo Proxy"),
  "Opening1-FateStayNightUBW.webm" => array(
    "title" => "Opening 1",
    "source" => "Fate/Stay night: Unlimited Blade Works"),
  "Opening2-FateStayNightUBW.webm" => array(
    "title" => "Opening 2",
    "source" => "Fate/Stay night: Unlimited Blade Works"),
  "Opening1-FateZero.webm" => array(
    "title" => "Opening 1",
    "source" => "Fate/Zero"),
  "Opening2-FateZero.webm" => array(
    "title" => "Opening 2",
    "source" => "Fate/Zero"),
  "Ending1-FateZero.webm" => array(
    "title" => "Ending 1",
    "source" => "Fate/Zero"),
  "Ending2-FateZero.webm" => array(
    "title" => "Ending 2",
    "source" => "Fate/Zero"),
  "Opening1-Free!.webm" => array(
    "title" => "Opening 1",
    "source" => "Free!"),
  "Ending1-Free!.webm" => array(
    "title" => "Ending 1",
    "source" => "Free!"),
  "Opening1-FullmetalAlchemistBrotherhood.webm" => array(
    "title" => "Opening 1",
    "source" => "Fullmetal Alchemist: Brotherhood"),
  "Opening2-FullmetalAlchemistBrotherhood.webm" => array(
    "title" => "Opening 2",
    "source" => "Fullmetal Alchemist: Brotherhood"),
  "Opening3-FullmetalAlchemistBrotherhood.webm" => array(
    "title" => "Opening 3",
    "source" => "Fullmetal Alchemist: Brotherhood"),
  "Opening4-FullmetalAlchemistBrotherhood.webm" => array(
    "title" => "Opening 4",
    "source" => "Fullmetal Alchemist: Brotherhood"),
  "Opening5-FullmetalAlchemistBrotherhood.webm" => array(
    "title" => "Opening 5",
    "source" => "Fullmetal Alchemist: Brotherhood"),
  "Ending1-FullmetalAlchemistBrotherhood.webm" => array(
    "title" => "Ending 1",
    "source" => "Fullmetal Alchemist: Brotherhood"),
  "Ending2-FullmetalAlchemistBrotherhood.webm" => array(
    "title" => "Ending 2",
    "source" => "Fullmetal Alchemist: Brotherhood"),
  "Ending3-FullmetalAlchemistBrotherhood.webm" => array(
    "title" => "Ending 3",
    "source" => "Fullmetal Alchemist: Brotherhood"),
  "Ending4-FullmetalAlchemistBrotherhood.webm" => array(
    "title" => "Ending 4",
    "source" => "Fullmetal Alchemist: Brotherhood"),
  "Ending5-FullmetalAlchemistBrotherhood.webm" => array(
    "title" => "Ending 5",
    "source" => "Fullmetal Alchemist: Brotherhood"),
  "Opening1-GekkanShoujoNozaki-kun.webm" => array(
    "title" => "Opening 1",
    "source" => "Gekkan Shoujo Nozaki-kun"),
  "Opening1-HaibaneRenmei.webm" => array(
    "title" => "Opening 1",
    "source" => "Haibane Renmei"),
  "Ending1-HaibaneRenmei.webm" => array(
    "title" => "Ending 1",
    "source" => "Haibane Renmei"),
  "Opening1-JoJo2012.webm" => array(
    "title" => "Opening 1",
    "source" => "JoJo's Bizarre adventure (2012)"),
  "Opening2-JoJo2012.webm" => array(
    "title" => "Opening 2",
    "source" => "JoJo's Bizarre adventure (2012)"),
  "Opening1-LogHorizon.webm" => array(
    "title" => "Opening 1",
    "source" => "Log Horizon"),
  "Ending1-LogHorizon.webm" => array(
    "title" => "Ending 1",
    "source" => "Log Horizon"),
  "Opening1-LoveLive!.webm" => array(
    "title" => "Opening 1",
    "source" => "Love Live!"),
  "Opening1-LoveLive!S2.webm" => array(
    "title" => "Opening 1",
    "source" => "Love Live! S2"),
  "Opening1-MachinedollWaKizutsukanai.webm" => array(
    "title" => "Opening 1",
    "source" => "Machine-Doll wa Kizutsunai (Unbreakable Machine-Doll)"),
  "Ending1-MachinedollWaKizutsukanai.webm" => array(
    "title" => "Ending 1",
    "source" => "Machine-Doll wa Kizutsunai (Unbreakable Machine-Doll)"),
  "Opening1-MayoChiki.webm" => array(
    "title" => "Opening 1",
    "source" => "Mayo Chiki"),
  "Ending1-MayoChiki.webm" => array(
    "title" => "Ending 1",
    "source" => "Mayo Chiki"),
  "Opening3-MiraiNikki.webm" => array(
    "title" => "Opening 3",
    "source" => "Mirai Nikki"),
  "Ending3-MiraiNikki.webm" => array(
    "title" => "Ending 3",
    "source" => "Mirai Nikki"),
  "Ending1-MM!.webm" => array(
    "title" => "Ending 1",
    "source" => "MM!"),
  "Opening3-MonogatariSeriesSecondSeason.webm" => array(
    "title" => "Opening 3",
    "source" => "Monogatari series second season"),
  "Opening1-NeonGenesisEvangelion.webm" => array(
    "title" => "Opening 1",
    "source" => "Neon Genesis Evangelion"),
  "Ending1-NeonGenesisEvangelion.webm" => array(
    "title" => "Ending 1",
    "source" => "Neon Genesis Evangelion"),
  "Opening1-Nisekoi.webm" => array(
    "title" => "Opening 1",
    "source" => "Nisekoi"),
  "Ending1-Nisekoi.webm" => array(
    "title" => "Ending 1",
    "source" => "Nisekoi"),
  "Opening1-Nobunagun.webm" => array(
    "title" => "Opening 1",
    "source" => "Nobunagun"),
  "Opening1-Noragami.webm" => array(
    "title" => "Opening 1",
    "source" => "Noragami"),
  "Ending1-Noragami.webm" => array(
    "title" => "Ending 1",
    "source" => "Noragami"),
  "Opening1-Oreshura.webm" => array(
    "title" => "Opening 1",
    "source" => "Oreshura"),
  "Ending1-Oreshura.webm" => array(
    "title" => "Ending 1",
    "source" => "Oreshura"),
  "Opening1-Parasyte.webm" => array(
    "title" => "Opening 1",
    "source" => "Parasyte"),
  "Opening1-Persona4TheAnimation.webm" => array(
    "title" => "Opening 1",
    "source" => "Persona 4 The Animation"),
  "Ending1-Persona4TheAnimation.webm" => array(
    "title" => "Ending 1",
    "source" => "Persona 4 The Animation"),
  "Opening1-PsychoPass.webm" => array(
    "title" => "Opening 1",
    "source" => "Psycho Pass"),
  "Opening2-PsychoPass.webm" => array(
    "title" => "Opening 2",
    "source" => "Psycho Pass"),
  "Ending1-PsychoPass.webm" => array(
    "title" => "Ending 1",
    "source" => "Psycho Pass"),
  "Ending2-PsychoPass.webm" => array(
    "title" => "Ending 2",
    "source" => "Psycho Pass"),
  "Opening1-PsychoPass2.webm" => array(
    "title" => "Opening 1",
    "source" => "Psycho Pass 2"),
  "Ending1-PsychoPass2.webm" => array(
    "title" => "Ending 1",
    "source" => "Psycho Pass 2"),
  "Opening1-SerialExperimentsLain.webm" => array(
    "title" => "Opening 1",
    "source" => "Serial Experiments Lain"),
  "Opening1-Shirobako.webm" => array(
    "title" => "Opening 1",
    "source" => "Shirobako"),
  "Opening1-StrikeTheBlood.webm" => array(
    "title" => "Opening 1",
    "source" => "Strike The Blood"),
  "Opening2-StrikeTheBlood.webm" => array(
    "title" => "Opening 2",
    "source" => "Strike The Blood"),
  "Ending1-StrikeTheBlood.webm" => array(
    "title" => "Ending 1",
    "source" => "Strike The Blood"),
  "Ending2-StrikeTheBlood.webm" => array(
    "title" => "Ending 2",
    "source" => "Strike The Blood"),
  "Opening-SuperDanganronpa2.webm" => array(
    "title" => "Game opening",
    "source" => "Super Danganronpa 2"),
  "Opening1-SwordArtOnline.webm" => array(
    "title" => "Opening 1",
    "source" => "Sword Art Online",
    "song" => array(
      "artist" => "LiSA",
      "title" => "crossing field")),
  "Opening2-SwordArtOnline.webm" => array(
    "title" => "Opening 2",
    "source" => "Sword Art Online"),
  "Ending1-SwordArtOnline.webm" => array(
    "title" => "Ending 1",
    "source" => "Sword Art Online"),
  "Ending2-SwordArtOnline.webm" => array(
    "title" => "Ending 2",
    "source" => "Sword Art Online"),
  "OpeningMilla-TalesOfXillia.webm" => array(
    "title" => "Game opening (Milla)",
    "source" => "Tales Of Xillia"),
  "Opening1-TalesOfXillia2.webm" => array(
    "title" => "Game opening",
    "source" => "Tales Of Xillia 2"),
  "Opening1-ToaruKagakuNoRailgun.webm" => array(
    "title" => "Opening 1",
    "source" => "Toaru Kagaku no Railgun (A Certain Scientific Railgun)"),
  "Opening2-ToaruKagakuNoRailgun.webm" => array(
    "title" => "Opening 2",
    "source" => "Toaru Kagaku no Railgun (A Certain Scientific Railgun)"),
  "Ending1-ToaruKagakuNoRailgun.webm" => array(
    "title" => "Ending 1",
    "source" => "Toaru Kagaku no Railgun (A Certain Scientific Railgun)"),
  "Ending2-ToaruKagakuNoRailgun.webm" => array(
    "title" => "Ending 2",
    "source" => "Toaru Kagaku no Railgun (A Certain Scientific Railgun)"),
  "Opening1-ToaruKagakuNoRailgunS.webm" => array(
    "title" => "Opening 1",
    "source" => "Toaru Kagaku no Railgun (A Certain Scientific Railgun) S",
		"captions" => "Opening1-ToaruKagakuNoRailgunS.ass"),
  "Opening1-ToaruMajutsuNoIndex.webm" => array(
    "title" => "Opening 1",
    "source" => "Toaru Majutsu no Index (A Certain Magical Index)"),
  "Opening2-ToaruMajutsuNoIndex.webm" => array(
    "title" => "Opening 2",
    "source" => "Toaru Majutsu no Index (A Certain Magical Index)"),
  "Ending1-ToaruMajutsuNoIndex.webm" => array(
    "title" => "Ending 1",
    "source" => "Toaru Majutsu no Index (A Certain Magical Index)"),
  "Ending2-ToaruMajutsuNoIndex.webm" => array(
    "title" => "Ending 2",
    "source" => "Toaru Majutsu no Index (A Certain Magical Index)"),
  "Opening1-TokyoGhoul.webm" => array(
    "title" => "Opening 1",
    "source" => "Tokyo Ghoul"),
  "Opening1-TonariNoKaibutsu.webm" => array(
    "title" => "Opening 1",
    "source" => "Tonari no Kaibutsu"),
  "Opening1-Watamote.webm" => array(
    "title" => "Opening 1",
    "source" => "Watamote"),
  "Opening1-ZankyouNoTerror.webm" => array(
    "title" => "Opening 1",
    "source" => "Zankyou no Terror (Terror in Resonance)"),
  "Ending1-ZankyouNoTerror.webm" => array(
    "title" => "Ending 1",
    "source" => "Zankyou no Terror (Terror in Resonance)")
)
?>
